keys:
  - &user_aarbour age1jtfn6xtwzg2n6jdjf3pkhzsw6ns5fqfexgyxk4k5cpxs79v3rv7qfhk05e
  - &host_rhys age1lfjjk4m0sh8cjdmmxfvh93yxvk53ufdna5gsfd5gnzrn78wdm9ashl35hm
  - &host_morrigan age15el767ldhcl7exa0z7v78chzmjthsadavlcnnzhpfqp4sj6fcvtq0f95tk
  - &host_lucien age1zcfj8lpt8sry4sq9khrsyur2f9j8pezppz3asxjcu55mr23d4ats8dzrdc
  - &host_sidra age1camvnsecm8hfnx66j7xg24lfgaeeamvtyr8kue0pdt5x92s5a9as9sew7r
  - &host_cassian age1lt0k6wfwl4drhg2wpkw4sazg5peymj5nrgn43mvsvkj0ua5ef4asdg2264
  - &host_dlrr age1s0rkwq0c75z0zlue23evq77wq0qg4lfq4cwk4myunkrsz3k8xg8s2s0ymp
  - &host_night age1rzwhhytjxxtz6jkz5xgzvvhvy883n92868h7ts0pv5dedglupa8qtgp4d5
  - &host_spring age1zjwq7dv4gypm94jssf2lg05652hw0g2l4lssaxnkcp09d7x24yfqsj2kfs
creation_rules:
  - path_regex: '(^|.*/)trove/.+[^/]$'
    shamir_threshold: 1
    key_groups:
      - age:
        - *user_aarbour
        - *host_rhys
        - *host_morrigan
        - *host_lucien
        - *host_sidra
        - *host_cassian
        - *host_dlrr
        - *host_night
        - *host_spring
