passwd: ENC[AES256_GCM,data:W4xuAxDOkCmV07MyRn2imO7CUDxhs6gssVmcQEIrKUquRmObIlhWvq+rYa6tGoHQ21jOGtTt/aq4I7ZVSVYpjuQYnfmPV++G7g==,iv:QCbTlfgSgNYv0AYL617FUUxKtlbNj3JOZPEoWtswuvs=,tag:UYIMxhyCZzMbWngRda3V6Q==,type:str]
age_key: ENC[AES256_GCM,data:qi0n3E1C+nrWOduGlkv1WrWyJ/FbwWwd0/xuEd5GWbv9gz4oQ3KieBP14giI61eHmwArXkgFebWYFaqcHeF+VKf9bran368NCEg=,iv:v6rwc6edWAYHVovfKlI0zwGazjDSBgENv56zWRrekQQ=,tag:3Yt4NfmTWx8ofQBQi+hShQ==,type:str]
id_ed25519: ENC[AES256_GCM,data:dKjE6jFs4F+gQVyJ2hrg3qmZz+9/9BT9Y87L52lzwZm4W53KJYNo/VxIVjDxPHBHplu5WYiXprbqQBXm+59XLfxO2UK7v1vmQsFaNMd3EckcXwamjVNkFGPjIkLxyCrCH4hvgfjYkVHDxIj+V1oGmoqkNUTesc/iS6dvHWusu0WjC5ciw1IDUGQ7rPfi5C6wXVW+uHQl+20iAWK71/y9dkeIwcRJFpXYQYTcG97VIr7sSvsiKEe6CCTKMQuMrCIgK5PQbAeTgZgosxkDEODFdF7ScXXuAcuR9ZPiN2gXqj97OD04axnqWCDdWNMgHl4eCLII9whs3ci9yCOcj+Dx2T4+Sj/0/IAXhVUowAwK9/pXOuv1rEESBAroztoBQJMaBNh0BmW7IP3g8l7Rn71fCh4VUMX995MjyU2b8WLTljS5dJve1f7ec6UmjUn40HXfvWLZY/aDbg9/156tIj1jb0/FYUGUo09Maispi1fcA5jj0tBPh9Uy0GiKbwWCr1gNjxTXAUdOT7Vkwdj7dxXi7jIDaq38IUBMjHvq,iv:yb64+ALwrQD7XOmGlT+I0qTZUL1o195L48oISVoDKno=,tag:mdouzg8IuHsRi1IS0MQCww==,type:str]
id_ed25519_pub: ENC[AES256_GCM,data:jWcK/u6Y7SfMmUkKHfBy6nfOu165fEsCljOe/DGMriT92dAqk54ZYGCUP8KHruHoeNB7RfMOHLbkC2daiZG8L+9Ga8rJlR6qBrq0tuiidSUcumvQmYZKyQ==,iv:W4yhHKy+pnzGcXxohANixGn/Sk2O5Lk/h1j6xsOqPEw=,tag:Uy5ibYupBVhcC3GZFrn3MQ==,type:str]
sops:
    shamir_threshold: 1
    age:
        - recipient: age1jtfn6xtwzg2n6jdjf3pkhzsw6ns5fqfexgyxk4k5cpxs79v3rv7qfhk05e
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBadkRKUHozQ0xhdXFDTVVC
            YmFiNFl0cDc4U2toM3VMNzM4ci8xeXFxRm5NCnhEemJKeGc5UXpLcUN3b0Z4S1hI
            WFRiekRNdi9TekFHMHFpLzZUMFRNRkUKLS0tIFFidEhqYzNSL1A2Smh0bk1UTjlD
            MHlyYnROczRzMEJTTGNPSUpuWWljL0EKBALpN0cYlkgf+lQ04PGFG0MKdvBoOrEX
            9zObcFKGZuT4QTPRWPVuJENNmWP9GBM96YNP3eGcrHGLZ5UPaAWUfg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1vqxhpv6pk5t0wxw2xxcgqm33dkutnmn93dmysp3p73dtdzhveqwqnrhxce
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVa2tCMjcrRmhKWXZJdHl3
            VS9iZmFaajVNZjRzcHJtVFlrMkVOdGJOelVrCmNXWWw4dVhSd2t0RHduOE1Xekx1
            YVVmYzhGUU9pbUFoei94MmFFQ3RWVFEKLS0tIGM1WjhYWE9YTm9iMUlObTh4R2hW
            UTRTUDVWNUhqUXlkYTJYRlYyNi9oRVkKMHxzcKSBoHea9V4UIrnR6TN8QUQROkA3
            7FQvNNmxewZ+hn5ToSxbP7JkPtk/gc5Fu/JPPoFu26B808u5nlK9LA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1sgvfec08pw9unyhf0q6mcm4p8t9qnq47mkx8q76ptf0y4v2lncnqwhlwcm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtMkcxRlFsNzNOWFJzQjZH
            LzdOYTE5SkZwYkQzTG5qeGx5eXZMalVKTlZNCkhtbExxL3p4YnI2dkdTZ2d0OHR3
            cnJFSG9yTnBRUWVrWG1jUU96NXdYT2sKLS0tIHc1WXBVRTR4WmcvVldHeHNCZm1U
            Y2hKV3RMYk5qdkgzT1VXYkZsKzZ2WUEKMKhWI4R0E3A6GqJDOnEB69m1xmbqLYc2
            9IQ0zKSi/xlN5OImXh+FuX2s8qoijDB44EQEm6cAv5sN/xl/LEx3QA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1lt0k6wfwl4drhg2wpkw4sazg5peymj5nrgn43mvsvkj0ua5ef4asdg2264
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvZ3JHcTc0YksvSS9LT2cr
            dU4xUGVFNzFkOC9DbWZQc1p5SXZJMTFRL0RzCitobGhIVlBwT1BxRjVwYkExSlpl
            R25aanlaQUZOYllpUy82Q3VmRXpEN0kKLS0tIHB0bXhOTTVEbm5LOGlxZXZuWkQx
            TW9QS2R6Y1Q3b0lCbHRuSmYzRVo2UkkKdQYMpoq1GFyc1iGG0PUuQrPaPbi5cyEr
            92UvB6GAmBIsIQ+WXUl+WSsdRM2QKp//y187vaGsrr+vg5MP39F1dg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1yptam40dlt97dmv6d0n9ytrwtxq9f2mqht8s7kdqjkmwax8nn4uq8hd9uh
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBESjNsRUZwOFh4cVJpc0hU
            NmJFU1UwbkQvWWt3emRBemhTSjFNTkdNeldVCnZWQUcrSjR1cUZkZ0dNdjU5V3FB
            akhnTERNZ3hWZjhvd3gzWndvTGlsN1EKLS0tIGpWbVordFNVaXlLUXRUU0ZIVlJv
            bExqdGFyQ21hMXp3QzBxb0JEZEJ6UlkK7kyC0gIhPelhYJ5FUEeQQl6UGSThQttt
            itUVBfjekaaB+wLSZn9FJl/p4XeO2KSveMP0AIRd+TlVoqpuhq4Ejg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-09-14T00:10:32Z"
    mac: ENC[AES256_GCM,data:eTSJvlGPMyTpTc+RQpnDiHgdipZ8SO8pF1v0viOLOun94fTTvgXDEFbKhninwJysTy4SSAxXkk74mWaWF8cGyiPRi4LRHWtCl5UgD/WqOaB27DSLb0kcGjX/Q9helDEcyxUEHM01ZzLpgv4tKRHhnKLA3bPWnQ6/1aRfz/+/3Q0=,iv:ZSwEemRbyJd0GZ45qOS+Bl5J8/MTQFRct3VXz3GXQ5Q=,tag:5nqv9AGrYCLb6ZirSuSPSA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.10.2
