passwd: ENC[AES256_GCM,data:W4xuAxDOkCmV07MyRn2imO7CUDxhs6gssVmcQEIrKUquRmObIlhWvq+rYa6tGoHQ21jOGtTt/aq4I7ZVSVYpjuQYnfmPV++G7g==,iv:QCbTlfgSgNYv0AYL617FUUxKtlbNj3JOZPEoWtswuvs=,tag:UYIMxhyCZzMbWngRda3V6Q==,type:str]
id_ed25519: ENC[AES256_GCM,data:dKjE6jFs4F+gQVyJ2hrg3qmZz+9/9BT9Y87L52lzwZm4W53KJYNo/VxIVjDxPHBHplu5WYiXprbqQBXm+59XLfxO2UK7v1vmQsFaNMd3EckcXwamjVNkFGPjIkLxyCrCH4hvgfjYkVHDxIj+V1oGmoqkNUTesc/iS6dvHWusu0WjC5ciw1IDUGQ7rPfi5C6wXVW+uHQl+20iAWK71/y9dkeIwcRJFpXYQYTcG97VIr7sSvsiKEe6CCTKMQuMrCIgK5PQbAeTgZgosxkDEODFdF7ScXXuAcuR9ZPiN2gXqj97OD04axnqWCDdWNMgHl4eCLII9whs3ci9yCOcj+Dx2T4+Sj/0/IAXhVUowAwK9/pXOuv1rEESBAroztoBQJMaBNh0BmW7IP3g8l7Rn71fCh4VUMX995MjyU2b8WLTljS5dJve1f7ec6UmjUn40HXfvWLZY/aDbg9/156tIj1jb0/FYUGUo09Maispi1fcA5jj0tBPh9Uy0GiKbwWCr1gNjxTXAUdOT7Vkwdj7dxXi7jIDaq38IUBMjHvq,iv:yb64+ALwrQD7XOmGlT+I0qTZUL1o195L48oISVoDKno=,tag:mdouzg8IuHsRi1IS0MQCww==,type:str]
id_ed25519_pub: ENC[AES256_GCM,data:jWcK/u6Y7SfMmUkKHfBy6nfOu165fEsCljOe/DGMriT92dAqk54ZYGCUP8KHruHoeNB7RfMOHLbkC2daiZG8L+9Ga8rJlR6qBrq0tuiidSUcumvQmYZKyQ==,iv:W4yhHKy+pnzGcXxohANixGn/Sk2O5Lk/h1j6xsOqPEw=,tag:Uy5ibYupBVhcC3GZFrn3MQ==,type:str]
sops:
    age:
        - recipient: age1jtfn6xtwzg2n6jdjf3pkhzsw6ns5fqfexgyxk4k5cpxs79v3rv7qfhk05e
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmRWRmb0EydWJxcjRKYkln
            ajlTODY1M3FKbFhVV2VPYUo5VVgwcUNQN21VCkpaYXh3RytyajdleGRjaUlVV1RB
            L0NqQ1FONGRDVUZsSVlFQi8rNERnODQKLS0tIGFJT2Y2akVWclhhTXFrRXl2VXZq
            TmpweVVnN2c0b0F3MFVaenp0RlArZnMKCKdLichMqtnNeYqUNBUGhWlt65sp65P4
            ucYdLZjjnAS+ExXtQ0kvjW8d6tBMZmSJo9ye9n0neSNka8kyrbT15g==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1sgvfec08pw9unyhf0q6mcm4p8t9qnq47mkx8q76ptf0y4v2lncnqwhlwcm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXU3NsbDBYM1VTTitiNVB1
            QzdERzArSmQ1UlE5OTB2bDJOa0JHOGtkQTFJCjFTVTN4TWMzN1hQdEw2K0pMTjhU
            KzRmaWxYVVBKeVBsTzhiK2tKdnRLZ2MKLS0tIHNYbGhIWkx5WEtmeVQ4R09xVW5t
            UndTeW1ERXhwUWZBNTlvTEM5TFphRzgKvr2DJTO0iFj1W1PCO+Fk01kU4aASEKGM
            uLKXbwzT7AxYZaEO7gUR7bO81SZHztDl+FkF+HSP+tU3W2kuInwQVg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1lt0k6wfwl4drhg2wpkw4sazg5peymj5nrgn43mvsvkj0ua5ef4asdg2264
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzSjNNaHQrKzI3Y3lmYTlm
            dkVRRENPUWREWGh0ZUpwMWljamgyL0c1STFFCjB2MGV3NEFEM2dFWGwrZFhQckpp
            a09nZ0Nkb2tEZFhaOWgvOFpNZGhOLzAKLS0tIFZhVzFlSU43VmRBRGNHK1dpUzdU
            UHF6ZE4wVWVwZ0FnSzdLS2hMeUZiamsKcqmYeA37dbU6wIdtO3V0q7LOa0FdJDYp
            j2/lOzxGRh3PwWv3pcNtR84EQps84FsXBzlkx+BWVuEca6U8d/HuUg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1yptam40dlt97dmv6d0n9ytrwtxq9f2mqht8s7kdqjkmwax8nn4uq8hd9uh
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJM2x2SEVyT0lrK2JmWnVv
            enhQK0EyNEhaMG9zM1NNY1kxdTdWUnQyamkwCjFkbUMyc0pLYW93bEl6enFNRG5n
            cVZGM1hzRVJTeDVHT0E2K2ZOcHozZ2sKLS0tIGhaL2ZYMC9mSFFkTVJjK1VUZWNs
            OVd1cVhDbzRwRXJSZUtsamxMQTZwVk0KgmO/5MLZMUtR++GHg+udp2WujREQlv35
            gcGpr42Upr32DenNgZ/6cWb4GlqdowcKDUCK9Kbq9bL/kpfRNnEiOA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-08-13T17:43:55Z"
    mac: ENC[AES256_GCM,data:GKtJ8V/yvj2kTsquTXKhx2Rr5rufFuWSC0nvH2kWkuNGTQCHyxkYWaYOKUyFuIlGIHHzwGqul6wTLrwxRqK5jWUYPjeDueu8ddBma/cpBq6ZHvXmKS7OmA6tzR2EwEmAi3/igJYdqnls/kxFR/RUiWOB6xX54r9X6eQOSC5vohI=,iv:6R/RRYoUd8SRZrkkna/6yy+wo3svxgF48KPHxZtzOXs=,tag:v2fCcNF4kYeRnN8Tr1mHMQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.10.2
