passwd: ENC[AES256_GCM,data:tUc7gOk060O2vSAHaX64qwPE7NP9z6eDLsqrGT2HKDEUFbcssrFTnI2dHr92+vvcypjYnmEYfvv6R1Pkku1jtVqIpiVtwiGITQ==,iv:nJ8XyQrNauJ53eDG73ZB/QlEUQt/16HWmmQouBje31c=,tag:Z1HUHG/mXL548Oot5zAvoQ==,type:str]
age_key: ENC[AES256_GCM,data:eOR/w/Tt666zGsrXPedNm/ubYHnJdhI8wbiFWI3dCi3TitFhneITA3TPfvsVtwwAXeUHKB9MYD7YwABS9/liEHSw6o9zABbGAMg=,iv:4YBP0dy4va6Q24NF2g68KrAvWoWd1m9UgF7VN06sees=,tag:5nCepKcfzTtV44G66+9MOw==,type:str]
id_ed25519.pub: ENC[AES256_GCM,data:t8u4jSpuNnhTOloh0EaBLbRdtN8jS74fbMu1tXgxnAuO2oAgOCcyhIS1wC+OII3AscVV8mAq7hK6RoK5JuVM5/6v2zS0WTsCCEr2cbq/+1nzLBYE5x5IhQ==,iv:StwznPhRjKX4dGvEf8Sx7eDLLtV6gOSHjLN9lC1LDzs=,tag:pls1KIBv8iH+GTMwpC7ejQ==,type:str]
wg_proton: ENC[AES256_GCM,data:Cu4Wz74IBCV3vpjuwuJAX7LjRuqBW+QW3ovY6V4h4WI22/fI6I8C1wMyGww=,iv:BXuW0Zf2pouR69XPkb0oSBlR3WpaWhIE04NzV4l8a3A=,tag:VvgELXlu+VrcwbIjnrsTlw==,type:str]
sops:
    shamir_threshold: 1
    age:
        - recipient: age1jtfn6xtwzg2n6jdjf3pkhzsw6ns5fqfexgyxk4k5cpxs79v3rv7qfhk05e
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5OGdUL0N2R3FzT0MycUxJ
            NTBPZmlWSzA0dy96U1dZWmJlR0tsVFoycFZFCmo3eHlYWGhZRDdxTitaS1QxTHFm
            cDY0TEl4NXNCTVZMWUp6RmtZWlZ3RlUKLS0tIEhlVlFxR2F6dTBNSW1HM1pQRmQ1
            ekwvMTBsK0JSSCtNa3BPbTJrYlpoMDQKNN/tVO59P+KfQ9Hjxkm0STY45uNn17lJ
            iSc5S0x01e/oqmnFBcdICN/vacnJ+YAmurpm5/Fn6t7aTyFre7dsFQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age15el767ldhcl7exa0z7v78chzmjthsadavlcnnzhpfqp4sj6fcvtq0f95tk
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtRjRoQ0N3M3JRcEJsak01
            WFRhVzB4eGxXWnY4b2ljd2tWZDQzN1FXcldFCjNnSHYzd2g3OVBNV21xL3pFWXZY
            TXVtSDh6NjhNaVlRR1BlSkRrVHUyak0KLS0tIDdEVVlZK1ZCWWJqclJ1MnduenYw
            b1RUcVRsNG8wUlZEK2hFbkJLUW40UWMKrefpQmBceYXCwGPY95OtGbWEalrIc8Le
            oReMA8p3vPae7IUl0kWfKDTNndfmb0g6LOWu5l8CY5oLi+JaqI1VHw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1sgvfec08pw9unyhf0q6mcm4p8t9qnq47mkx8q76ptf0y4v2lncnqwhlwcm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKSDJjcTdBTElSeUp1WjJ4
            Mk5QMlNMb2N3UG81allnWWtqVW9vVFhuOG5JCkNKTk84Uzh2SXgybWxXTHRWUXpw
            S2dXb2hIaVVOK0IxTzl6YzI2bk0waDgKLS0tIEJ4WDM2czZPQmxsaThzTTNadWs3
            UkhSeEFGZVg2UUZiejZJbEhMN2FSVTgKEAPCDilOu0foJfIlfRi1obtZVwg2gocZ
            VZXQpsJUAecmHWGoUniBosU05Mk7wKctCXAV6WO+I4VyrWp5xn6EzQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1lt0k6wfwl4drhg2wpkw4sazg5peymj5nrgn43mvsvkj0ua5ef4asdg2264
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkMXNnNFVqWlZzS25ROTQ2
            czJtUVBuWlhlMXpOMC9iWFF3Ky9zOThJZVE4CjF4VWRFVzdwMGczOFZoNXpHelBS
            UzU1WCtsMm9xekhySHJ0Tll2MXV5L1UKLS0tIFc5amFpMVpDdHB0RUJEU2hycXhN
            OSsveDdxVWFMd1Y5d1ZlZDJ0RHgyQlUKirYfbcWAYEhg1RW45T9ImtuNcqTvrCri
            oK90hibT1gdRfmQNqDvrf4EAp7VXnfRNphstH+sI5kGcOhmR9fjQcg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1s0rkwq0c75z0zlue23evq77wq0qg4lfq4cwk4myunkrsz3k8xg8s2s0ymp
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvSWVGcGd5R1JLZ2EwczJH
            dlg0ZktzekIwUFJHcy9kaC90L2diRitlM20wCkkvK0NtWDBYZlNuU3hqUDFDd05u
            bVJGY1FtR1dvUTZzZGhEdm1wMlhXb3cKLS0tIDl2ZVF2VTN1M2xzSjJ2UlJTMEZ3
            UXhzWXNuZFRiY2xpNWRsNTVGVFZ3cGMKxsZDuUrfr1fFoBdVCOdqplQuMXxZUtRs
            Z+sxYF2aPdYQLyrtWxOlvGTRXXqAiAqb2x26duhrDxYpLt8bxZiZ/g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-09-17T20:28:31Z"
    mac: ENC[AES256_GCM,data:PkJtzKwxCpS8GvfjxHHaOPgDp/B+OSA64GcyKdT1nOcjG4t7ZYZu8P2xbTtCXE2LLy5Y96XQ8xEzwiC/aoRSn0lCDi0gpplu4KT9IU3JXy7VEVpqlrwUp3bw9svanJqOoAEsiIHmdogX7PbQ9yd1qUPwhxI6V5oX4eppssftSv4=,iv:eeTkgjAtihOuUz9MsOuPHHSpfAl3Adu2PQZhdazcUTY=,tag:i/uMINBGPbx3bDEMk+1Tnw==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.10.2
