passwd: ENC[AES256_GCM,data:tUc7gOk060O2vSAHaX64qwPE7NP9z6eDLsqrGT2HKDEUFbcssrFTnI2dHr92+vvcypjYnmEYfvv6R1Pkku1jtVqIpiVtwiGITQ==,iv:nJ8XyQrNauJ53eDG73ZB/QlEUQt/16HWmmQouBje31c=,tag:Z1HUHG/mXL548Oot5zAvoQ==,type:str]
age_key: ENC[AES256_GCM,data:eOR/w/Tt666zGsrXPedNm/ubYHnJdhI8wbiFWI3dCi3TitFhneITA3TPfvsVtwwAXeUHKB9MYD7YwABS9/liEHSw6o9zABbGAMg=,iv:4YBP0dy4va6Q24NF2g68KrAvWoWd1m9UgF7VN06sees=,tag:5nCepKcfzTtV44G66+9MOw==,type:str]
id_ed25519.pub: ENC[AES256_GCM,data:t8u4jSpuNnhTOloh0EaBLbRdtN8jS74fbMu1tXgxnAuO2oAgOCcyhIS1wC+OII3AscVV8mAq7hK6RoK5JuVM5/6v2zS0WTsCCEr2cbq/+1nzLBYE5x5IhQ==,iv:StwznPhRjKX4dGvEf8Sx7eDLLtV6gOSHjLN9lC1LDzs=,tag:pls1KIBv8iH+GTMwpC7ejQ==,type:str]
sops:
    shamir_threshold: 1
    age:
        - recipient: age1jtfn6xtwzg2n6jdjf3pkhzsw6ns5fqfexgyxk4k5cpxs79v3rv7qfhk05e
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBadkRKUHozQ0xhdXFDTVVC
            YmFiNFl0cDc4U2toM3VMNzM4ci8xeXFxRm5NCnhEemJKeGc5UXpLcUN3b0Z4S1hI
            WFRiekRNdi9TekFHMHFpLzZUMFRNRkUKLS0tIFFidEhqYzNSL1A2Smh0bk1UTjlD
            MHlyYnROczRzMEJTTGNPSUpuWWljL0EKBALpN0cYlkgf+lQ04PGFG0MKdvBoOrEX
            9zObcFKGZuT4QTPRWPVuJENNmWP9GBM96YNP3eGcrHGLZ5UPaAWUfg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1vqxhpv6pk5t0wxw2xxcgqm33dkutnmn93dmysp3p73dtdzhveqwqnrhxce
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVa2tCMjcrRmhKWXZJdHl3
            VS9iZmFaajVNZjRzcHJtVFlrMkVOdGJOelVrCmNXWWw4dVhSd2t0RHduOE1Xekx1
            YVVmYzhGUU9pbUFoei94MmFFQ3RWVFEKLS0tIGM1WjhYWE9YTm9iMUlObTh4R2hW
            UTRTUDVWNUhqUXlkYTJYRlYyNi9oRVkKMHxzcKSBoHea9V4UIrnR6TN8QUQROkA3
            7FQvNNmxewZ+hn5ToSxbP7JkPtk/gc5Fu/JPPoFu26B808u5nlK9LA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1sgvfec08pw9unyhf0q6mcm4p8t9qnq47mkx8q76ptf0y4v2lncnqwhlwcm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtMkcxRlFsNzNOWFJzQjZH
            LzdOYTE5SkZwYkQzTG5qeGx5eXZMalVKTlZNCkhtbExxL3p4YnI2dkdTZ2d0OHR3
            cnJFSG9yTnBRUWVrWG1jUU96NXdYT2sKLS0tIHc1WXBVRTR4WmcvVldHeHNCZm1U
            Y2hKV3RMYk5qdkgzT1VXYkZsKzZ2WUEKMKhWI4R0E3A6GqJDOnEB69m1xmbqLYc2
            9IQ0zKSi/xlN5OImXh+FuX2s8qoijDB44EQEm6cAv5sN/xl/LEx3QA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1lt0k6wfwl4drhg2wpkw4sazg5peymj5nrgn43mvsvkj0ua5ef4asdg2264
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvZ3JHcTc0YksvSS9LT2cr
            dU4xUGVFNzFkOC9DbWZQc1p5SXZJMTFRL0RzCitobGhIVlBwT1BxRjVwYkExSlpl
            R25aanlaQUZOYllpUy82Q3VmRXpEN0kKLS0tIHB0bXhOTTVEbm5LOGlxZXZuWkQx
            TW9QS2R6Y1Q3b0lCbHRuSmYzRVo2UkkKdQYMpoq1GFyc1iGG0PUuQrPaPbi5cyEr
            92UvB6GAmBIsIQ+WXUl+WSsdRM2QKp//y187vaGsrr+vg5MP39F1dg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1yptam40dlt97dmv6d0n9ytrwtxq9f2mqht8s7kdqjkmwax8nn4uq8hd9uh
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBESjNsRUZwOFh4cVJpc0hU
            NmJFU1UwbkQvWWt3emRBemhTSjFNTkdNeldVCnZWQUcrSjR1cUZkZ0dNdjU5V3FB
            akhnTERNZ3hWZjhvd3gzWndvTGlsN1EKLS0tIGpWbVordFNVaXlLUXRUU0ZIVlJv
            bExqdGFyQ21hMXp3QzBxb0JEZEJ6UlkK7kyC0gIhPelhYJ5FUEeQQl6UGSThQttt
            itUVBfjekaaB+wLSZn9FJl/p4XeO2KSveMP0AIRd+TlVoqpuhq4Ejg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-09-16T21:05:00Z"
    mac: ENC[AES256_GCM,data:+lHCENvf0xdf/GzyDIDD1uX8epeGnhLTlSVrSZX19MMDAsvfNSWlHeNEyND6By+owFolM48j7I2RDNqCMegFc79vDleHZlYmDQ4PX/jye60Uo1VGtR8mqJ8Ilg4lW2KnxsJnR7nrzJsdS2cdazqYFA7WTJxuG7d6dphuMlw2syw=,iv:lWEretecYab4SG4muweMI4UjRpe7cVtNWOEw8Y/we50=,tag:8BNj7S+x26GJn9K4lAolLQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.10.2
