passwd: ENC[AES256_GCM,data:tUc7gOk060O2vSAHaX64qwPE7NP9z6eDLsqrGT2HKDEUFbcssrFTnI2dHr92+vvcypjYnmEYfvv6R1Pkku1jtVqIpiVtwiGITQ==,iv:nJ8XyQrNauJ53eDG73ZB/QlEUQt/16HWmmQouBje31c=,tag:Z1HUHG/mXL548Oot5zAvoQ==,type:str]
age_key: ENC[AES256_GCM,data:eOR/w/Tt666zGsrXPedNm/ubYHnJdhI8wbiFWI3dCi3TitFhneITA3TPfvsVtwwAXeUHKB9MYD7YwABS9/liEHSw6o9zABbGAMg=,iv:4YBP0dy4va6Q24NF2g68KrAvWoWd1m9UgF7VN06sees=,tag:5nCepKcfzTtV44G66+9MOw==,type:str]
id_ed25519.pub: ENC[AES256_GCM,data:t8u4jSpuNnhTOloh0EaBLbRdtN8jS74fbMu1tXgxnAuO2oAgOCcyhIS1wC+OII3AscVV8mAq7hK6RoK5JuVM5/6v2zS0WTsCCEr2cbq/+1nzLBYE5x5IhQ==,iv:StwznPhRjKX4dGvEf8Sx7eDLLtV6gOSHjLN9lC1LDzs=,tag:pls1KIBv8iH+GTMwpC7ejQ==,type:str]
wg_proton: ENC[AES256_GCM,data:Cu4Wz74IBCV3vpjuwuJAX7LjRuqBW+QW3ovY6V4h4WI22/fI6I8C1wMyGww=,iv:BXuW0Zf2pouR69XPkb0oSBlR3WpaWhIE04NzV4l8a3A=,tag:VvgELXlu+VrcwbIjnrsTlw==,type:str]
nebula_ca:
    cert: ENC[AES256_GCM,data:Xa3FSmNIS3275xkH9BwlbVInsaLEeHGAMFAdgCBgfW8DcP40iw8rggsPQSx5flZW2OJ98RFI9rbv3qRx8+8b0p+pbDaPH+EIl7xfrYrmcx+HGumWpEEm97rQXwJDgG2oy4sFh0Wt3EI/5UwyClP5f91ufEXjpEsyZDMARBmSI06AkNcWjmFKORxkWnox3sij3oo+0YsxB7kfTbnYSJ/m4epOV3NgjgL50tdKLlR2pcUfTTmxMDCm/uGFFeWcPbftSKZb00dZMuwo4hGY0QVa+U7xzMfQOedvcD9sq+2mCluHW+7Ecdqm1JNulEkV2lqNCIg3SlXpDCVNuhU=,iv:91lXQwrQkarg0iimCuqlb+qZ5zWBbObgfBg85pb8Ypw=,tag:F50hBrOKwpKB7oRynfhpkA==,type:str]
    key: ENC[AES256_GCM,data:5fI64KHjOIjHQG1CXZAaJNttnuFhxz1Ktupjm62t4TtfwQxR+3UMPatuwe0c5sFmIbw71+WM23tkssSmtiun0X3Pz0XePFyWahzsgzMXZwDnG/HVkbvTridkwmr8ex6K83tu1W+JGEGVM2w5mPP6HDd3kkWzOuGJBZQ8QPlhQL6Aey3Z2+zCFeXixUcm/qJDddGdxG/DioplNEP7yofMiO/8O+EdqQpF/GSt3Gm5,iv:OZh7yOYdY2dIMAjrncX5MOGkynq8L+tEbkZcbTX4taI=,tag:TjgjWkU6qON3K5vzlPQZLg==,type:str]
sops:
    shamir_threshold: 1
    age:
        - recipient: age1jtfn6xtwzg2n6jdjf3pkhzsw6ns5fqfexgyxk4k5cpxs79v3rv7qfhk05e
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvaGNJeXF3ajg4bEFLWFRD
            b245aFkzelVwOEYrTkY4NktuSzQzZ2lHeXdnCnNEN0NHS2NKZ1FySzY5WWt6bmtS
            czZHbWN3bTJpdDVTSzMwc1FuOXNGT1kKLS0tIDdKTmpQMmdJQWJ3MEppSVoxMDRp
            cHJoZDRyZG5TZGIxcHc0ZVFLUmh4eGMKBkKSHUcbbu7jjn4Taq2UwImIodO/RGwU
            vCN72ipOMuw/rTD7hUD9PkL5lDWyq1AIRVPj4kXbVjEai/ZFvJaMHg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1lfjjk4m0sh8cjdmmxfvh93yxvk53ufdna5gsfd5gnzrn78wdm9ashl35hm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwSXl6eDNQcjJmVnhzSUdD
            Lzg3a09xM3Z1ZnAzTzY5TzF1TnoxNXZ4Vm5NCnFCTkQ3bm9BaWx2czBNRW5jZDBQ
            UCs1UlVTdStrTzgrZEdJR0d3c2NieUUKLS0tIDJWaDB4Y2wyTDFaU1hUSjNoUXQz
            Z1QxNkx4bmNFNXNYLzVtVFVsQWN3S0EK4k1MnOU9hG4BhuhPcTBdD4dbMGvL/VsP
            big8cXOjzpMT+ISGXYTVyGtA/p7NsASA251TomIYeX4AWRYcfSl63w==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age15el767ldhcl7exa0z7v78chzmjthsadavlcnnzhpfqp4sj6fcvtq0f95tk
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHeEFDRlI3YUZvYUNldjU5
            V1VzYTBxekt4NEdIbU12VTkxcHArMFBnZGdNCk1TVnRpelRqRkowNzJqRFpRRjBq
            RkJvSy8reVlETW15T21uT3JYQWlRbXcKLS0tIDJSdUVMcTYyQWJIODVPRFNxNUJE
            SHJ0dnhRZGNTWG9rT05LNXFxWXg5WWMKeagUPGXKRdR5IdjuLzCuqGCRSnoJyNUR
            dJ1vcMhP7sRCiNjn7dqMOTXjIMgoysWz8a48D45y52Jo5+vm+H+TVQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1zcfj8lpt8sry4sq9khrsyur2f9j8pezppz3asxjcu55mr23d4ats8dzrdc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZNnhBZUN4UTR3enVDM1Zi
            RjFHQjlpQWQ2M3hONUs2bDUzQnljK2lSYTBvCjVUbVpGY0pzTWZPTC84Y0orcjJi
            YkQ4UnN3L1NpTjRCUFc0SitBdHY4MDAKLS0tICtCVy9IMVh5eWxFTVprRHlJRlov
            T2xmVG52SkdSYkJDbXNIMWRYYjV2MkEKgKkHAtNDmB4UJFQRdBtacPN+XOwXvn8g
            nntYCHtVlq65ziZi2HjYKhQCNgAk6QUhGKknKftd0u1+8vBZlvXBAA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1camvnsecm8hfnx66j7xg24lfgaeeamvtyr8kue0pdt5x92s5a9as9sew7r
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOQkF1eXFieEIveGpQKzJr
            ZE4zSnhZUmpNdXJ2bTJGUUhGY1BtRzlldEZzCmkrUHV5djBrSmVIZEErQlE5UVRa
            YjBUcWFaWmZ0L2NGR1N3WW1kK2l6aFkKLS0tIFE0Z2F3c0UyVnRjazdGdWV0UHhx
            YzBlMHNzQmJLM3JKdVdHWS8yZHdXNEkKtC54KfFZObrmsfzZ/GA1STKJKq9rAOl3
            3SsI/1Ys9XBYMVNO3g50b9UzKO/bOxPkzhNx9e99/q7eKa4UgU2jlQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1lt0k6wfwl4drhg2wpkw4sazg5peymj5nrgn43mvsvkj0ua5ef4asdg2264
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1OGpTeE1sNjJmUnRlc3VG
            UnU0ZjFLTjlCd2REdmxYWnFoTit3RkQrc2dBCjRoc3dZb0tWSGh2UVVtWTl6Z3Zr
            RWdhcnFwRzJKQnNHajM1UWV3UGV3ZEkKLS0tIHRBQVR4cVIvaHFFQjJrdVp4eFVh
            VUJ2QVc3elNiUnI0OWN5a2UyNXd5WncKv+5/jLJMQ6brIUDF8e0F984LvgzrJiLH
            5M3tITJWa5q2vOYAusF4D7TmATwx3ECNu/zjXsGdI1jkXCNhCCwKJg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1s0rkwq0c75z0zlue23evq77wq0qg4lfq4cwk4myunkrsz3k8xg8s2s0ymp
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3eHE1WDZwV2w1RU5UdlY4
            ZVFrUDdlVjFVQ1J4YnFWWVdQNUpJWkdDTVhzClR0L3kzQ0Y1V2V2bExSZjNkWUlP
            NlIxUlRGbnRaTFNvVEc1bUZXcWZBVkkKLS0tIFhVaCthWnZ2eUxzckc3QWRHODNC
            bXdReHliU3VWRmRMOWExbXJsVnY2OTgKBGlHFZRzaywzjI1Gy31O7Y3dCLzT7tBM
            eX3VoenDNuQSnv8D/zNh9XG98ODrDP8CQSRknu5JtuWvfIK4hP6MeQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1zjwq7dv4gypm94jssf2lg05652hw0g2l4lssaxnkcp09d7x24yfqsj2kfs
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZRW1COVU2aGVJblgxbkJn
            YXJKbDV6aTlORVZDQ05BUVN4bXFFYTNJYVU4CkNvNjJSY0l2RmhUMFRBWW9nbEpU
            Z0lqYnRHUWs0UmhZL0hyM3lDQ2dKUDQKLS0tIER3SnhIbzZkUkhlL1o3MHRFZEZU
            SFdjVlhOTWRmeFVuK3JVSitPMDY1ZUUKYBan6+QSO4bhOmXm1gjRHYvAR1LSpQjO
            q7pGOPglBeorXCg/rXr9LI2GqVjwDa+NQpcMNZ1KeXbhX89cjsBfhQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age15pca2knfgtvh7erg7meupltmpl8hr42skwzfythd5qesdlz075msv92e6e
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKWEJ5emppQ0dZWDIybHVy
            ak0zc01EYW94R2Z0eHF6UDFKNkJiV3hNc3dNCndhUHFVRkZEeDMzSkRqd0tiMExs
            Uis1QnBSczlvOW9NT0NoVm9RUDZLb1kKLS0tIEZQL2tVZWJ0a1VYTGNiQWpmcHcy
            bnp2amFPYVRYeUZacXJJNnZPbFVrc2sKQDSNVDS3RNahPp8PejQUr2nJveGENup8
            PpVTJeU0iaip35n6y5QeuJoZEFI9+EfNdjU4snplaTZohI7UqbM6UQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1pcp35euleycnthrl7dr29x0awyhklr6aaucrkehzgytrg224dvlsnlhsej
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpOHBoZEh5d0hBaGRwOEo1
            NExndng0NStrUU9QdlpheENXMm4xdklVOG5zCmxiQ0JFRnBtYkNnZWVKQjJrd3Mv
            eXVMRy95TkV5b0xzdFZWNWEyY2k3aGcKLS0tIHh1K3JMbmg4TnJyaTg2a1Bvbmhl
            TW5SWVNWc3dNQmRsd01DaE1KMy83UGMKJiaok4l2H6a+5CyXKCLRzhwMgKK0UzlE
            Lv1Vi6wfpkfIbrJVmRFfJHgczzjwE8Kg2LKLtrIeqHz9qJ4yYgInJA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1fmkwgp27mw9xm7sjdpkn8wfl99xcg2xd76842a2gexxhlgqdny7qrqw5un
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTY2N4bGhGZzlhTFM5ZHdm
            QXZ4aHJQY1R3TmRNd2xUWHhRWldiSnU5VEVVCnlnMG5OY2JGVWJLOTh5NzdsM2Vt
            UGZwaEdEb29ZT3BMQUxWSGM5MU0rWjgKLS0tIG5JMUQ4WWorT1VuT1FnUjh2VVIr
            TUczT2ZPcGlOSloxd2ZNV2tJSTZKdmcKWpWpzBS6bxNCOYikU+dZR3Gj7A8bJ4FI
            qLYgHUzL+zZHqVMBbk6jVLSQzt5D+d2V8L2Uvw9kwfQsYBF72BmLSw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age10tuprldqv2qqla237dfatvql4qxkzlp3yyqqvhfrwv3rlnqfxajs0cs0kc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRdmxIWXY1VDNxbGFFV00r
            WHZvQm9jU05tU2J6TFJ5bkhlZEV2VEViaUdRCkplaFRIYTNxbDJSOGdNWGMvNjVs
            aEpQOWJEUW1lWVFYcVVQTnpsdDlqRUUKLS0tIFl4MkFja3VFOWJJNXNoSGpFMzd4
            NkIyNzNCZzd1ZWNhRkdrNlFkc3UzYXMKLZGTZMkps+l+bWDLKc5+Yio+v17soelM
            eNzSMewuvhF64KAdJyy+rNXqDo+aaWL7I7VUVJ0rq8j0c8/onnKfVw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1rzwhhytjxxtz6jkz5xgzvvhvy883n92868h7ts0pv5dedglupa8qtgp4d5
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZVkZnNU5qOGVvK1JESkNB
            SjhuYUV3L3pBTHBoektPcDJWWHpnNkQ3K0h3CkwyNS9XSnBXeW1Rb21iUEdEaXpl
            ZDZqY0Q2cXNmT1FJWll5OUZyQnBibGcKLS0tIGVWUVJXa1hESkNUcEx6ZUd5OG9i
            S3o0bUxVakVlZTNrMzJkMy9lWW5zUDQKFwp5FQcwfd/qgz1ES1ohFc+t+llGdjZu
            ALF4Cx4RlUg2qCL4sDjDSdYeBsJFA3wFFXYaouNON8zZTQf993Acng==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-10-01T05:12:02Z"
    mac: ENC[AES256_GCM,data:uStSEj6LmxN5ZIVQ1LZLeddC8SkGGqSDPb2pD4byTbEEb4b4WSQcwGrgiUqejDPrSQTTSJihqdfckhIGGn4juWYNYL8mq16kDnzdTqgKXltYMUUp302CKlcVhy0Wmkr4TepGxp5Xx3O7NT4NixBVxj8hYXydDTsYDvYU5JTWmQA=,iv:Dy62E+5lOiX78t40W5XF8Sz4/y7V9nfwNNdh7It7A6o=,tag:BJo9WanHt1TuMCePP3R45g==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.10.2
