passwd: ENC[AES256_GCM,data:W4xuAxDOkCmV07MyRn2imO7CUDxhs6gssVmcQEIrKUquRmObIlhWvq+rYa6tGoHQ21jOGtTt/aq4I7ZVSVYpjuQYnfmPV++G7g==,iv:QCbTlfgSgNYv0AYL617FUUxKtlbNj3JOZPEoWtswuvs=,tag:UYIMxhyCZzMbWngRda3V6Q==,type:str]
id_ed25519: ENC[AES256_GCM,data:dKjE6jFs4F+gQVyJ2hrg3qmZz+9/9BT9Y87L52lzwZm4W53KJYNo/VxIVjDxPHBHplu5WYiXprbqQBXm+59XLfxO2UK7v1vmQsFaNMd3EckcXwamjVNkFGPjIkLxyCrCH4hvgfjYkVHDxIj+V1oGmoqkNUTesc/iS6dvHWusu0WjC5ciw1IDUGQ7rPfi5C6wXVW+uHQl+20iAWK71/y9dkeIwcRJFpXYQYTcG97VIr7sSvsiKEe6CCTKMQuMrCIgK5PQbAeTgZgosxkDEODFdF7ScXXuAcuR9ZPiN2gXqj97OD04axnqWCDdWNMgHl4eCLII9whs3ci9yCOcj+Dx2T4+Sj/0/IAXhVUowAwK9/pXOuv1rEESBAroztoBQJMaBNh0BmW7IP3g8l7Rn71fCh4VUMX995MjyU2b8WLTljS5dJve1f7ec6UmjUn40HXfvWLZY/aDbg9/156tIj1jb0/FYUGUo09Maispi1fcA5jj0tBPh9Uy0GiKbwWCr1gNjxTXAUdOT7Vkwdj7dxXi7jIDaq38IUBMjHvq,iv:yb64+ALwrQD7XOmGlT+I0qTZUL1o195L48oISVoDKno=,tag:mdouzg8IuHsRi1IS0MQCww==,type:str]
id_ed25519_pub: ENC[AES256_GCM,data:jWcK/u6Y7SfMmUkKHfBy6nfOu165fEsCljOe/DGMriT92dAqk54ZYGCUP8KHruHoeNB7RfMOHLbkC2daiZG8L+9Ga8rJlR6qBrq0tuiidSUcumvQmYZKyQ==,iv:W4yhHKy+pnzGcXxohANixGn/Sk2O5Lk/h1j6xsOqPEw=,tag:Uy5ibYupBVhcC3GZFrn3MQ==,type:str]
sops:
    age:
        - recipient: age1jtfn6xtwzg2n6jdjf3pkhzsw6ns5fqfexgyxk4k5cpxs79v3rv7qfhk05e
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwMXpIOGdpZ28zZEl5SHZV
            ZEhjSk1wTUZtZjlMOHA2K3RnRmFaV1Q2NXdzCnJJSFVlSXJSMjFXaXZBcUhZM3Zp
            L01Td0lXTVVJYWdpODU0ekVqeHVDdk0KLS0tIC9rdFFWN3dlQjA1dWoyKzhzd21t
            RnZqTTBqU01YbFFpbG9abDhpc2wrdEUKTJdCunBDTvl8nx5flqoQk79mYzSJhRl8
            DtTPUqwOafd5E8kpYuTubAtMqDIcNtGXDaOKaEkr9/cbdL4oym7q2A==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1sgvfec08pw9unyhf0q6mcm4p8t9qnq47mkx8q76ptf0y4v2lncnqwhlwcm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvc1B3S09pK3VFaW0xYTZR
            Z0p5Tks3R2s0eDkvTFpNdW1XZWlDOVNNbURNCmpwUEQyajN2TGJ0c3lIakNIL3pv
            NkNMb1NDbDl4UkFHVlM4UjNCRGExWWMKLS0tIFBqU1BvV0NlSUtBUElEcEl6WkU3
            Yjg5cUlUUzU5OXRLSEVZbGwrWGdjLzAKig0tPYhBqP6kGduzAl41rmN+qVFLNo/0
            grWRQ1Y5J6zPWcuU7FRdaEjZELBqDKrkDzHEnUw4DruYdUQXBqF+Lw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1lt0k6wfwl4drhg2wpkw4sazg5peymj5nrgn43mvsvkj0ua5ef4asdg2264
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvak5yVlczRk81MEFhMzc3
            ZkIydldOVG10N1BDemxtTTlFbHI5TFlkQmhZCjM0QzFwejZ3SFJaYW43dUU5amc1
            QlRlcmlHcGhNY3YxeWpsaU1Jci9wNlEKLS0tIDFmaWF1alhEMDlXUDVtZWRUV21Y
            M1NudkYxMzVqQ3AvekpUVW9XL2czcXcK23NEuCuqEJCgQP3R79zfR7vGnjM6bm9+
            OoTCpjSqLWmUkI1vMD/yEipcNZ9+4nOWs4dAf1nghDblSu5GqXzeAQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age18unqwzucq32gc8zwgu3z9g4ur07y3ckgjsemes5u3tf4eg3v6daswqrp97
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOdEw1by9kQitGOXArQ2Q1
            R3lRbE9jajZsQU5hYjd5eE5CdzhLdWVsNnhRCnQ2dmczT1BvQWx2TVQ1ZkJtK2Yy
            YmRWeUNJcW82T05SQjVmenF3WGVHTEUKLS0tIFNtYmd1ZGNnNWU2aXE0c2ViQW9O
            aHF6dTNxMk5oMTY3MUFaV0xNRFRRcG8K7GLQaG3DNYUZm4LtO4CJh6GABy1FU/Lz
            mLvwFDPCMlVbUn80umjzlHJi7oCBtunShV1Ywn/3TkwoJKdB/nS7ag==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-08-13T17:43:55Z"
    mac: ENC[AES256_GCM,data:GKtJ8V/yvj2kTsquTXKhx2Rr5rufFuWSC0nvH2kWkuNGTQCHyxkYWaYOKUyFuIlGIHHzwGqul6wTLrwxRqK5jWUYPjeDueu8ddBma/cpBq6ZHvXmKS7OmA6tzR2EwEmAi3/igJYdqnls/kxFR/RUiWOB6xX54r9X6eQOSC5vohI=,iv:6R/RRYoUd8SRZrkkna/6yy+wo3svxgF48KPHxZtzOXs=,tag:v2fCcNF4kYeRnN8Tr1mHMQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.10.2
