passwd: ENC[AES256_GCM,data:tUc7gOk060O2vSAHaX64qwPE7NP9z6eDLsqrGT2HKDEUFbcssrFTnI2dHr92+vvcypjYnmEYfvv6R1Pkku1jtVqIpiVtwiGITQ==,iv:nJ8XyQrNauJ53eDG73ZB/QlEUQt/16HWmmQouBje31c=,tag:Z1HUHG/mXL548Oot5zAvoQ==,type:str]
age_key: ENC[AES256_GCM,data:eOR/w/Tt666zGsrXPedNm/ubYHnJdhI8wbiFWI3dCi3TitFhneITA3TPfvsVtwwAXeUHKB9MYD7YwABS9/liEHSw6o9zABbGAMg=,iv:4YBP0dy4va6Q24NF2g68KrAvWoWd1m9UgF7VN06sees=,tag:5nCepKcfzTtV44G66+9MOw==,type:str]
id_ed25519.pub: ENC[AES256_GCM,data:t8u4jSpuNnhTOloh0EaBLbRdtN8jS74fbMu1tXgxnAuO2oAgOCcyhIS1wC+OII3AscVV8mAq7hK6RoK5JuVM5/6v2zS0WTsCCEr2cbq/+1nzLBYE5x5IhQ==,iv:StwznPhRjKX4dGvEf8Sx7eDLLtV6gOSHjLN9lC1LDzs=,tag:pls1KIBv8iH+GTMwpC7ejQ==,type:str]
wg_proton: ENC[AES256_GCM,data:Cu4Wz74IBCV3vpjuwuJAX7LjRuqBW+QW3ovY6V4h4WI22/fI6I8C1wMyGww=,iv:BXuW0Zf2pouR69XPkb0oSBlR3WpaWhIE04NzV4l8a3A=,tag:VvgELXlu+VrcwbIjnrsTlw==,type:str]
nebula_ca:
    cert: ENC[AES256_GCM,data:Xa3FSmNIS3275xkH9BwlbVInsaLEeHGAMFAdgCBgfW8DcP40iw8rggsPQSx5flZW2OJ98RFI9rbv3qRx8+8b0p+pbDaPH+EIl7xfrYrmcx+HGumWpEEm97rQXwJDgG2oy4sFh0Wt3EI/5UwyClP5f91ufEXjpEsyZDMARBmSI06AkNcWjmFKORxkWnox3sij3oo+0YsxB7kfTbnYSJ/m4epOV3NgjgL50tdKLlR2pcUfTTmxMDCm/uGFFeWcPbftSKZb00dZMuwo4hGY0QVa+U7xzMfQOedvcD9sq+2mCluHW+7Ecdqm1JNulEkV2lqNCIg3SlXpDCVNuhU=,iv:91lXQwrQkarg0iimCuqlb+qZ5zWBbObgfBg85pb8Ypw=,tag:F50hBrOKwpKB7oRynfhpkA==,type:str]
    key: ENC[AES256_GCM,data:5fI64KHjOIjHQG1CXZAaJNttnuFhxz1Ktupjm62t4TtfwQxR+3UMPatuwe0c5sFmIbw71+WM23tkssSmtiun0X3Pz0XePFyWahzsgzMXZwDnG/HVkbvTridkwmr8ex6K83tu1W+JGEGVM2w5mPP6HDd3kkWzOuGJBZQ8QPlhQL6Aey3Z2+zCFeXixUcm/qJDddGdxG/DioplNEP7yofMiO/8O+EdqQpF/GSt3Gm5,iv:OZh7yOYdY2dIMAjrncX5MOGkynq8L+tEbkZcbTX4taI=,tag:TjgjWkU6qON3K5vzlPQZLg==,type:str]
sops:
    shamir_threshold: 1
    age:
        - recipient: age1jtfn6xtwzg2n6jdjf3pkhzsw6ns5fqfexgyxk4k5cpxs79v3rv7qfhk05e
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwaG5GS3B3MUJpczFTK0Mr
            SVRpeXpUVHU0aTZ2ZUV3bEc1Um0rdWpGa2dNCjVTRmlJV0tVUE5aY1QvOU5IOW95
            WE1kN2VpQm03dXFPaFpkL2VLT2lpN0EKLS0tIFR5UXY0eVRuQXR4SXFwNjArTnZa
            eCtsdTAyREJFTGU0S01xUWRBdDFWZUUKM/acvN5yhd0Vf7KzSigp4xWYb01yHZ/6
            LhLgH2Cd7md5VC5Lm477GyhLJRRZVJJWQXk8oXoatPY6HqiNKMsp8w==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age15el767ldhcl7exa0z7v78chzmjthsadavlcnnzhpfqp4sj6fcvtq0f95tk
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBuSExsbG5JSmd1WHFCcTFi
            czNHbXlJbUdTcVJkUktVYm9tR241OEc1clVJCnROaElJbHBSMjdMNkw5SlZnOVpY
            TkZ4R3J0b0tEaElacWdQMTFoWk9MUEkKLS0tIHliN25TVURXemdhZEZmbW9jb0ZE
            d2d4QVl0RHBNQVB2MW9TL1FGcHg0elUKuT+UG9Izsaxwmf/aUks/g42X+80nc77B
            p2oZSwxSExkvPaGBk8R1od/TvZzlMtDCuwUUxISWQbHHfPRPajx6sg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1zcfj8lpt8sry4sq9khrsyur2f9j8pezppz3asxjcu55mr23d4ats8dzrdc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBETDlmdWJmMmc1SGs4UHBa
            RzJhVzNWb1hrSFJpM0NOWmthekltUGNsSHlrCnduTjVZbmNGWGtiSkw5N3ZveThT
            YzhXYXIyTFl2UjFKaXlEQ2ZnSVU3U1kKLS0tIHBJR1NIYnMrYVY3U29adWNwVGww
            Nll3SkxXMjdLdnJ1aEVFamZhMG5pRkEKnnId9CJLHV+8I09cDOgWYeO4Xl1a9EON
            qLt9U22VDZMLID7sUB8wK1WRakI8Dt5y4el0lHj5gpVZROvxEEAFjA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1camvnsecm8hfnx66j7xg24lfgaeeamvtyr8kue0pdt5x92s5a9as9sew7r
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2MFBicVVIbjBOblJFd1dE
            K3lyYVA3NS9RaEc4KzByTmZ3OG1VK0lmS3pVClkwVTcyK2N3NkJoNC93cDUrNWVJ
            eXZKL0hraE5CdURPQzV3eDRxeUJpRFkKLS0tIFhVSXFwK0pRQnNkdlA2SzdyTjds
            MGZYOFM0OUtxTTYyTFFUUnh1ZlRBVnMKPmhjxJ6w/LWRMUTiEI7CqZ/kgpn06PB6
            PBaQKBoaJkxnId2iw4XCCS9TzEd9nhUzxsyzoJammgqoaFk+z2egzw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1lt0k6wfwl4drhg2wpkw4sazg5peymj5nrgn43mvsvkj0ua5ef4asdg2264
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNcjEwcmJmVENXd2tycURO
            VmQ5TXY3cEhuTEZaUTZQMkIyRXZ6czBYTWpJCi8vVXZtYnBiUTVQNnJhVlBPTm80
            TTI2TkdjeHcwalZBcjM4aUtvZ280UHcKLS0tIHkxM1VOUldDZDBTSU41T21jdytE
            UENCT3ZZQlA0dDFkdnh2dVM1eXMwclUK/aW7zCF+Kr1C6oYpL4YCW2OrcTqpRB2U
            hJEnBglIlJ2dAo3dhKzMOgaEyIRJYQ4BEPyRE3cs6fos9UE/zRgzhw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1s0rkwq0c75z0zlue23evq77wq0qg4lfq4cwk4myunkrsz3k8xg8s2s0ymp
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzRlYveWU2R3FlWEFMNFUy
            ODE3SjYrT2M3SjF3OXJ1NVZZYkZDMG9GMmo0CmZLRS9QdVFSTlQxUFljWm9nWWZP
            dGpvaXRGdGpuTjY5TjRnTk5ueVoyOW8KLS0tIDNSdU9WbHZMN0JCN3hlZm5rRHFz
            QXNQSnJibTZkK09JU2pyVzZ6WmkxSHcKgADq+3CxKJtGAHjJmo8tnrVfG8qzZ+ak
            GPTiz7Ugj7kJF9Hc79nYdsNDnjYy42OLcCMboMpKDvt3nla19PUuZw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-10-01T05:12:02Z"
    mac: ENC[AES256_GCM,data:uStSEj6LmxN5ZIVQ1LZLeddC8SkGGqSDPb2pD4byTbEEb4b4WSQcwGrgiUqejDPrSQTTSJihqdfckhIGGn4juWYNYL8mq16kDnzdTqgKXltYMUUp302CKlcVhy0Wmkr4TepGxp5Xx3O7NT4NixBVxj8hYXydDTsYDvYU5JTWmQA=,iv:Dy62E+5lOiX78t40W5XF8Sz4/y7V9nfwNNdh7It7A6o=,tag:BJo9WanHt1TuMCePP3R45g==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.10.2
