passwd: ENC[AES256_GCM,data:tUc7gOk060O2vSAHaX64qwPE7NP9z6eDLsqrGT2HKDEUFbcssrFTnI2dHr92+vvcypjYnmEYfvv6R1Pkku1jtVqIpiVtwiGITQ==,iv:nJ8XyQrNauJ53eDG73ZB/QlEUQt/16HWmmQouBje31c=,tag:Z1HUHG/mXL548Oot5zAvoQ==,type:str]
age_key: ENC[AES256_GCM,data:eOR/w/Tt666zGsrXPedNm/ubYHnJdhI8wbiFWI3dCi3TitFhneITA3TPfvsVtwwAXeUHKB9MYD7YwABS9/liEHSw6o9zABbGAMg=,iv:4YBP0dy4va6Q24NF2g68KrAvWoWd1m9UgF7VN06sees=,tag:5nCepKcfzTtV44G66+9MOw==,type:str]
id_ed25519.pub: ENC[AES256_GCM,data:t8u4jSpuNnhTOloh0EaBLbRdtN8jS74fbMu1tXgxnAuO2oAgOCcyhIS1wC+OII3AscVV8mAq7hK6RoK5JuVM5/6v2zS0WTsCCEr2cbq/+1nzLBYE5x5IhQ==,iv:StwznPhRjKX4dGvEf8Sx7eDLLtV6gOSHjLN9lC1LDzs=,tag:pls1KIBv8iH+GTMwpC7ejQ==,type:str]
wg_proton: ENC[AES256_GCM,data:Cu4Wz74IBCV3vpjuwuJAX7LjRuqBW+QW3ovY6V4h4WI22/fI6I8C1wMyGww=,iv:BXuW0Zf2pouR69XPkb0oSBlR3WpaWhIE04NzV4l8a3A=,tag:VvgELXlu+VrcwbIjnrsTlw==,type:str]
nebula_ca:
    cert: ENC[AES256_GCM,data:Xa3FSmNIS3275xkH9BwlbVInsaLEeHGAMFAdgCBgfW8DcP40iw8rggsPQSx5flZW2OJ98RFI9rbv3qRx8+8b0p+pbDaPH+EIl7xfrYrmcx+HGumWpEEm97rQXwJDgG2oy4sFh0Wt3EI/5UwyClP5f91ufEXjpEsyZDMARBmSI06AkNcWjmFKORxkWnox3sij3oo+0YsxB7kfTbnYSJ/m4epOV3NgjgL50tdKLlR2pcUfTTmxMDCm/uGFFeWcPbftSKZb00dZMuwo4hGY0QVa+U7xzMfQOedvcD9sq+2mCluHW+7Ecdqm1JNulEkV2lqNCIg3SlXpDCVNuhU=,iv:91lXQwrQkarg0iimCuqlb+qZ5zWBbObgfBg85pb8Ypw=,tag:F50hBrOKwpKB7oRynfhpkA==,type:str]
    key: ENC[AES256_GCM,data:5fI64KHjOIjHQG1CXZAaJNttnuFhxz1Ktupjm62t4TtfwQxR+3UMPatuwe0c5sFmIbw71+WM23tkssSmtiun0X3Pz0XePFyWahzsgzMXZwDnG/HVkbvTridkwmr8ex6K83tu1W+JGEGVM2w5mPP6HDd3kkWzOuGJBZQ8QPlhQL6Aey3Z2+zCFeXixUcm/qJDddGdxG/DioplNEP7yofMiO/8O+EdqQpF/GSt3Gm5,iv:OZh7yOYdY2dIMAjrncX5MOGkynq8L+tEbkZcbTX4taI=,tag:TjgjWkU6qON3K5vzlPQZLg==,type:str]
sops:
    shamir_threshold: 1
    age:
        - recipient: age1jtfn6xtwzg2n6jdjf3pkhzsw6ns5fqfexgyxk4k5cpxs79v3rv7qfhk05e
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxSTdNUklhY3M3K01NRDZv
            bThvMVhrTmltR25NTGNFTzQrZnNlZmFQdkVnClRFc0dycy9hWGhxSHcyREl2M29w
            aTR3UitBTFRBSjJTWGQ4ajM2Z2M0VEEKLS0tIEpONkJKbVA0RnlvN0xhN3RRaDV1
            azhFaHhLRk5ZRGlUblJrbkRQNTdhNXMK/IjC26CJj6QUUBw2pvTVmBEhW/9D3nXM
            I4wdZlm89QwSxJSPHlXgN5dAIhgBAuc7m0wb1DDbC+GrOxdVvOdAEw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1lfjjk4m0sh8cjdmmxfvh93yxvk53ufdna5gsfd5gnzrn78wdm9ashl35hm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLUjR5K3lkQld3N3NUMG1R
            dUFuSHhaRXphajNkZnBLZVk4akcrOCtKSkNJCnJ2QU40a2NLYVVvcVFrSlVkVXpq
            WDBBeFpMSEZ4b2ZPa1ZTOG1uQzk3ZkEKLS0tIGZUUjFDTmF2T3FpaDZ4N2x1VXpS
            UFZtUDNIeUZmRlBKd2U0bkl6bEFHMTQK5bbGQM2W2g7PqQm44KLQSNmCXgiHWefe
            OBBPttedfXoUZwl3Dy5XHMZF56KDnk77Sh1+UjLD7kJWud1gFJ8Ecg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age15el767ldhcl7exa0z7v78chzmjthsadavlcnnzhpfqp4sj6fcvtq0f95tk
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkSnE0YURUMkxCVVF4NHg4
            SE9NelREQk5kYVQrOThSRTRteWM4dThqUmhBClJwcnY1czNOZDFuaTM4b01TODJi
            R04renIwMzlWdWIzcm92U0RtNUNNZUkKLS0tIGQrSmlqc3dZMElpZngyNzYyQ1VI
            N2dXMXRYdTloSU5MMWhrNkZ2eEFNb0kKKOYA1UwVI55GIzW9ybVh/Q2KxINlwPya
            LFRFM43pBWM/P/Jwf1vUWbDX7gO3uR7JgYel8IXHSWinn8htCVLRQg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1zcfj8lpt8sry4sq9khrsyur2f9j8pezppz3asxjcu55mr23d4ats8dzrdc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSTTNCcGZoMVl5KzFmd3pP
            NVJrUTE1ZGdhODdzWUJrZis0STFBYW1JZ2dvCnJKQmVKWjl4bTVWOXRiZEx1N2Ri
            cFVqQnNTR01YMmE4eGVRQkNGazJheW8KLS0tIGhocndSUlhOVmNQbWUyR2tmYUhn
            MkdqV09kK1RqVDYwdFNsWFpXUHhBK1kKAmJ9nPzi5q/P89HQ6BUOTsofAEe+4RYY
            j0ykbogVo9zDGFIjJqIyZamWSOJVQnPfvEIJ86jRUTtkwv1lNaEFlg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1camvnsecm8hfnx66j7xg24lfgaeeamvtyr8kue0pdt5x92s5a9as9sew7r
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXZHhGL09qZlEyd0pHRHV0
            L1gwMnN2ZWV4ZnZBOTFrQmZERG5Obk1iZFhZCnI5M2NiRHRDTk5hd0d2WEF3SnVr
            YUd2Tk9vazV4aGFzNzBLWUU3ZGJVREEKLS0tIHNCRlZQeHJ2bDQ2QUUxaGhiQmdT
            VXZUWEhVZG8yWGM4bDRSTXJtQ0YweVEKFVd0KtuL1ltQindQNVzs8xBN63mc4tV4
            Y2Y8yG++J7nj9rUPZCBMAQ/2c1Ee+Ac2BsXK91vDR+PNItH/JGLWsg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1lt0k6wfwl4drhg2wpkw4sazg5peymj5nrgn43mvsvkj0ua5ef4asdg2264
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGUllhWm0zWjk4Z1RRUGgx
            RFF6UFJxVUxuRHJZN3FRcUUvQnV6MEZ6dUF3Ck1Ea0MwS2k0QmhFbFl1RVYwLzdN
            K0ZFRzIwbTlJcmpncmROUGdxRThEbEEKLS0tIHVNYnVYbGtzK1R6eWs4OVNtNG9L
            MXJ5QUMwMEMyYWdRdlhORmdrVS9OeWMKxafjMVwMYep97ichkzcd9XtSeF+DvBSg
            iKvXRVjahxTiunjyDwwLYvnflL/YAuFk74PKcj7RP5Hf30oFxSK3bQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1s0rkwq0c75z0zlue23evq77wq0qg4lfq4cwk4myunkrsz3k8xg8s2s0ymp
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUaitTNnNqdEF1LzQ0NVBz
            V2JIMGg0ODJ1eFE3U0xvY3pKTnU5bytiQnc4CjhzOStkeG9kcjBvaDQ1UWJDYXQ0
            cENoSkRlNWcrd2lvTmVZdE5oQTEzZncKLS0tIExjNTBpcjBOeGZ4SldMenJFTlZC
            YWdYSDdMdXcvVVlSSEhpRGJyV3hPaW8KT6YGwwtATRU2Ixo+qHISomHE3vN0XyKA
            Ac4l/sCB3cHHzAjAGAul2oSla70RsnJMt6hNIoVPurXhGgz8+KtjuA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1zjwq7dv4gypm94jssf2lg05652hw0g2l4lssaxnkcp09d7x24yfqsj2kfs
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSWVVpMmVVaTlkSnlEc3pW
            cDdxUUtSWjdyN3QrbVZTSURESmo0WHF1M0M4CjVIY0xyL0lVZ1lCODViN3E3QXRv
            YUNvem1Rbzk3QW1GM21OU2I5b3cxbUkKLS0tIDZOcUdQaFcza1B5cEduc0Fra2gw
            QUJtdEZPMkpNMUsyOUc1VENxSmtmRlUKoWi4IGhBiWSEC3xPyQ+bJvrSQhpf0JK1
            hzrs70sSueCAvIXywqtQyw0xKi9/HCqPhIDmdMLVxsHdqfV5u9eT1A==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age15pca2knfgtvh7erg7meupltmpl8hr42skwzfythd5qesdlz075msv92e6e
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlVGcyU3lUeEtqZmdOdDNE
            OWk3RXovTzE3RE42aE9Ca0huQjA0MXFndUNNCkNaL1cwZGNOQ3pQOEVmSVBEaFg5
            WjZUV1RwU0UreCtiWkNOeFVVM1pBa0kKLS0tIDhMQ29KRFJ0ODdCK1VXc2tMUVJU
            dzFzYzMvbXpkREZRSGFTcWRPaXJ3L3MKPPr4PIglNm9Mf/VXMIDOTtju4Pa0vP4g
            U0gdS0JQjAkQQEi3iWQuKEcW/34xBTM8CuvSoSYB7trvnc49REqvpg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1fax4rzcv58s6wfzqzwjxjz4c4f0dcwahwzj675fvmu0ken6p23qqrlat47
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTcnQxcWQrZWF6QTgwQ0xi
            Q1NKVXpCRzFsN1FhOWx6R1R2NnVQMHhZK2tRCjlnbExQRWpOcmlxV3pzbm5LKzla
            TFV1cHZmWk0yNUxZV1NNVnNobVhUKzQKLS0tIEtQa29PbkJJcGVYWXRLRnVZNHlU
            aXA2SjlldnB1S0pMTWtlVUJ4V3RoTW8KzLCKFZBuXKJ/y1m8b4jd48ZCem5K3fD6
            2xxLQkLeKVCuUMvTdVFTjFCryttYjrg4wUWq0M8ycwStKWYIbYNXmQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1pcp35euleycnthrl7dr29x0awyhklr6aaucrkehzgytrg224dvlsnlhsej
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5ekM5bld4QmthVGFGS3Nk
            TnRDZ20waTZlcGZYb1JBVkN2K1hnQzVsa1hBCkFoSjhxWXJaeHU5Ny9wMWJiUFln
            MmhEQVVDYmxsOVhvNHZkZUxTRlBNazgKLS0tIHhVekt5aU5UdFp1QmRIUDlIdW4r
            Vm5pOUcwUE8rK3RCNGNSdGFiSE90WVEKZ1BsexYzks4pc0hNERIDT9E1Ar5Q4V7p
            608zTi4j9ngbYpIndwWtaYDRL1vI6HOa7eFkoVigBCOGqiJHHRPatw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1fmkwgp27mw9xm7sjdpkn8wfl99xcg2xd76842a2gexxhlgqdny7qrqw5un
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpcWphTkhlTU9UVEFsSXFY
            eWp6dUdUbzUzQWZka2Q5cUVMWFdOTCtSOTJZCjNHdGYzRG5KR2ZjVXMwalJ3MkNh
            M2hOZzhEc1JONGlFbko5VnZKVkNTdE0KLS0tIERvTFVoSlRLcityTytQQ0EwZUdW
            OXdiN0h4cjNsOGVoVTJSN0ZQRE5qencK+bZu9hSJcogDoxH+oTGH3ntD+3XKlcP1
            ucfirK7eeqHdbFcYSB/3iz/Ls6eZE8aQWlroZxDCvmLRmC9RcqT+5A==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age10tuprldqv2qqla237dfatvql4qxkzlp3yyqqvhfrwv3rlnqfxajs0cs0kc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAyQ2ZxdXpiUUcvREowU1dK
            bU8zUzZDV2NMVDFDNDJRUjQ5VHMyM0Yza0FVCjFBMVlhYXg3VHlaOXpGSkpnUjhu
            WkJZRHY1UzNqUWszbXhNNUpnL3JNM1EKLS0tIE9kd2RxSC9NRTV4M1QyeXFTa2Ri
            MkRsS21CZnZJRmFHNlFKWnFTdDZDRkUKWvWRQn6f8T6MZlbE++KELRvxSi76SUXJ
            md1JNi/3kFGtI4vk6mA89JAwyMQUdd9sK44MEvuy3YoGbeGyxAJVTA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1rzwhhytjxxtz6jkz5xgzvvhvy883n92868h7ts0pv5dedglupa8qtgp4d5
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCOExPZzE2Y2REWnZXYzNt
            eWZBZnlqc2daak9uY0NmUWFJa3FrS0ZVN25RCnZ6QUFVS28xRjBCWkNXMjVLdWM0
            UndJeldIQWtqRy9IYjZETWVvMVozKzgKLS0tIGlMcjRMTWhWanNkWVlQZXRjR3RE
            YUYxRFFVTFd4OFEzYXZkWldobVVmcEkKcVhrOOuMYpxCGtfvua78sxmwkN6gbebY
            KNhC1shZ8u3AVdWPUwhDNWtl/eomOQ5/xwNmMgyQAJI/L8yCkHPw7g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-10-01T05:12:02Z"
    mac: ENC[AES256_GCM,data:uStSEj6LmxN5ZIVQ1LZLeddC8SkGGqSDPb2pD4byTbEEb4b4WSQcwGrgiUqejDPrSQTTSJihqdfckhIGGn4juWYNYL8mq16kDnzdTqgKXltYMUUp302CKlcVhy0Wmkr4TepGxp5Xx3O7NT4NixBVxj8hYXydDTsYDvYU5JTWmQA=,iv:Dy62E+5lOiX78t40W5XF8Sz4/y7V9nfwNNdh7It7A6o=,tag:BJo9WanHt1TuMCePP3R45g==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.10.2
