passwd: ENC[AES256_GCM,data:tUc7gOk060O2vSAHaX64qwPE7NP9z6eDLsqrGT2HKDEUFbcssrFTnI2dHr92+vvcypjYnmEYfvv6R1Pkku1jtVqIpiVtwiGITQ==,iv:nJ8XyQrNauJ53eDG73ZB/QlEUQt/16HWmmQouBje31c=,tag:Z1HUHG/mXL548Oot5zAvoQ==,type:str]
age_key: ENC[AES256_GCM,data:eOR/w/Tt666zGsrXPedNm/ubYHnJdhI8wbiFWI3dCi3TitFhneITA3TPfvsVtwwAXeUHKB9MYD7YwABS9/liEHSw6o9zABbGAMg=,iv:4YBP0dy4va6Q24NF2g68KrAvWoWd1m9UgF7VN06sees=,tag:5nCepKcfzTtV44G66+9MOw==,type:str]
id_ed25519.pub: ENC[AES256_GCM,data:t8u4jSpuNnhTOloh0EaBLbRdtN8jS74fbMu1tXgxnAuO2oAgOCcyhIS1wC+OII3AscVV8mAq7hK6RoK5JuVM5/6v2zS0WTsCCEr2cbq/+1nzLBYE5x5IhQ==,iv:StwznPhRjKX4dGvEf8Sx7eDLLtV6gOSHjLN9lC1LDzs=,tag:pls1KIBv8iH+GTMwpC7ejQ==,type:str]
wg_proton: ENC[AES256_GCM,data:Cu4Wz74IBCV3vpjuwuJAX7LjRuqBW+QW3ovY6V4h4WI22/fI6I8C1wMyGww=,iv:BXuW0Zf2pouR69XPkb0oSBlR3WpaWhIE04NzV4l8a3A=,tag:VvgELXlu+VrcwbIjnrsTlw==,type:str]
nebula_ca:
    cert: ENC[AES256_GCM,data:Xa3FSmNIS3275xkH9BwlbVInsaLEeHGAMFAdgCBgfW8DcP40iw8rggsPQSx5flZW2OJ98RFI9rbv3qRx8+8b0p+pbDaPH+EIl7xfrYrmcx+HGumWpEEm97rQXwJDgG2oy4sFh0Wt3EI/5UwyClP5f91ufEXjpEsyZDMARBmSI06AkNcWjmFKORxkWnox3sij3oo+0YsxB7kfTbnYSJ/m4epOV3NgjgL50tdKLlR2pcUfTTmxMDCm/uGFFeWcPbftSKZb00dZMuwo4hGY0QVa+U7xzMfQOedvcD9sq+2mCluHW+7Ecdqm1JNulEkV2lqNCIg3SlXpDCVNuhU=,iv:91lXQwrQkarg0iimCuqlb+qZ5zWBbObgfBg85pb8Ypw=,tag:F50hBrOKwpKB7oRynfhpkA==,type:str]
    key: ENC[AES256_GCM,data:5fI64KHjOIjHQG1CXZAaJNttnuFhxz1Ktupjm62t4TtfwQxR+3UMPatuwe0c5sFmIbw71+WM23tkssSmtiun0X3Pz0XePFyWahzsgzMXZwDnG/HVkbvTridkwmr8ex6K83tu1W+JGEGVM2w5mPP6HDd3kkWzOuGJBZQ8QPlhQL6Aey3Z2+zCFeXixUcm/qJDddGdxG/DioplNEP7yofMiO/8O+EdqQpF/GSt3Gm5,iv:OZh7yOYdY2dIMAjrncX5MOGkynq8L+tEbkZcbTX4taI=,tag:TjgjWkU6qON3K5vzlPQZLg==,type:str]
sops:
    shamir_threshold: 1
    age:
        - recipient: age1jtfn6xtwzg2n6jdjf3pkhzsw6ns5fqfexgyxk4k5cpxs79v3rv7qfhk05e
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4UkE2RWF6bFkzRUpISzRo
            N1duZnc0QkpheGNkUEtUbU9YVDcvYTBvM0FzCm9zTTlha1R4M3hXMlNjQTdvempB
            cEFYYTVxcUg3aEtENks1SjVRRFMyTW8KLS0tIHlDT3dsdE1EWWpTTXM2RnpNZjlJ
            MlMvTHRBVU5YWk9IVEVWUG5SYnFBUzAKodGGEMBiU0Va81gZtl+dPI7hEoLahvqu
            nHFwR6vpl0H8fucLfuioIqLqDjY1piVMDAWxrP61vHLPVOSd55Jtsg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1lfjjk4m0sh8cjdmmxfvh93yxvk53ufdna5gsfd5gnzrn78wdm9ashl35hm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxZ2tMVmFZR1dIWW94Y2Rr
            c3lzbXNQaVU2aUNIcW9BbkNIWVIxNXVPbmx3CkF3YThSY1lpK1pja1JUMGZma0ZD
            K1RrMWsrV2svcExqSWRtU0FFVTZ5djQKLS0tIG9nTVJlMG5VTys3UXVJNFhTS0pM
            dTRVWW9CZUdxcWdRN0ZORENETFBmaTgKYKnKk5MBgBnMb41Y1LZvkTOa8ZSkXzb1
            X1fxhY4hVnuN8KuZJZVv2fqIq5gXGorikbTmKApxXC+epKxyOVA0Gg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age15el767ldhcl7exa0z7v78chzmjthsadavlcnnzhpfqp4sj6fcvtq0f95tk
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArWnE1VXNVOWdxR3MxSm1s
            b0JUUnpaV0FmVkpiTnhCVlcxbjNtNWEwYUdBCjBDZjJoeXIzanlPVTh1SzJERUMr
            Z09RRkVpdUxHSGJzNHgwaGY2MThVL3MKLS0tIFNwdE1mRVVVS1pQaTVhVlVYYS9z
            UHZDVFM4SHI0NkdxTzROS29tanRVbzAKHSyeRDdJ6r9K2sBKly3hohJT5Hu40Dj9
            CZgZYtsZuZd6H1nxvhF6nXXfqncjfl+/EwTA6TFdp7Qy5erQsAN+VA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1zcfj8lpt8sry4sq9khrsyur2f9j8pezppz3asxjcu55mr23d4ats8dzrdc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzNE84QnNDUXNwWkZoNHNS
            SUNhL1JtOXBhSnFad1I0V2ZNNlV0Z3IwVUdzCi9SOWdFQitpNE1SYlQzNituMzYv
            WEUzS2VXSno4SWpCSHFnMHAybXZZSG8KLS0tIHc3S20rMkh0dCtlclNJWXVmK1Fq
            Q1NaR09NVjFMWlZjNEJ3cUNLMVdVMHMKdg8JOYMRXHt3kzt6AhX5scDwx4v+z2HG
            Lupo80n4MN8KraV3urnh1OFQ5eQ4Ajrw+25lIMQ+1jzwCmLmxFIawg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1camvnsecm8hfnx66j7xg24lfgaeeamvtyr8kue0pdt5x92s5a9as9sew7r
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0ME9Hek03Zm81N0c0R2h3
            U1JKbDRoWHhiWkxoVTMzdUdoWSt3eXBWTnc4CjlWUDIxYXhoeElYakdPZmhONEtG
            VG03WC90V3dSemJESGYzRXRSTDhRdE0KLS0tIFZHQkdhZEtNekR0a09IZzRtd0ZL
            bm5YN3NWczlwWkdnREh0UURtQUxndGsKRxV+jwFf6MbmzlWJKcXPI9yb9fdgCEKk
            hAW+xLH+lQST9SqQFaPPXPj9e/JZMeJVFpFXDSsQK7+d53u5QEJwsA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1lt0k6wfwl4drhg2wpkw4sazg5peymj5nrgn43mvsvkj0ua5ef4asdg2264
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFejNQalBaQWpBTlFLTEdQ
            YVNTTmlFT1E1MlI3MUxKNzdwcDBwUW9qNXk0Ckt6TjhpdDhYaTAvbklGK01qQ0FM
            RnlRdGIyUEREa0hqMUFDK1k4Z2wyUUUKLS0tIFFXemdkeHJ3cnBUWnNmS3hidjNx
            d0laYzBDVTJGRzgyQUtocnI3UDJIelUKNCh6qNXxjYCa8pjkMH+l6C378JDyILH8
            7GPFO+EncMsMzMv6U21RkvxSiJRLUQpkUFnvYTn+Or9cf8tvkLnP/w==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1s0rkwq0c75z0zlue23evq77wq0qg4lfq4cwk4myunkrsz3k8xg8s2s0ymp
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQYUxUUlNSd2lNajYreWxG
            SGNwc0NodTkrVzBuamVqVjdwdXBwNEIyTWkwCm9PaHkwRWlxVW10N2ZUUGp4d1VB
            elNadE9ZYnl1dGllb2l5d0Y2QlF3REkKLS0tIEtBVWNnQWt3Z2hJQ1BSTGlCd2tD
            aXMvd2YzRE9LMFZRUlZEUW9TbW0xcWcKnVD21Ber3IWpkPqvT4ES8emOHwRWmvvf
            SpHytdsWfyVso5mt5+ps8bu7T0LeRLeALtVrmihtp0uEVzfVKIoHdQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1rzwhhytjxxtz6jkz5xgzvvhvy883n92868h7ts0pv5dedglupa8qtgp4d5
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOTzR6c0NsNlRXNnZXUllq
            K2NRbU9hbENpblhmdUtwaHdoMUNVZks4aEhBCjl1MTNmU2tub0NFM2RkYW9oZ21Q
            N3pmT0t4TTY1RHV4UnFCTmIzVTlkYkEKLS0tIHJQaE8yMHlIWXlNYzhsUEhPTUVD
            YXEyTGRWQmdpWFBEbVo0N1ZLTU5xVEUKJrdKa6oOJLEkWXAqOpZQrSQQpxi4L3gg
            3LtDUxhupx0ODvFOcF/a2wEOe3z1SsSGt90rYOcTWxCMr8LvEyLfgw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1zjwq7dv4gypm94jssf2lg05652hw0g2l4lssaxnkcp09d7x24yfqsj2kfs
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2TGRqMGdkT01uc3ZqSUMr
            SnJOTFNvdWU1b3BqWUhLdjJhUmVtUE1jUDM4CnlXbXA1NzJvcDVUR1d2d1hSNjll
            RGRmRTdTREd6Ylovd1dzWTRiZDNOSDAKLS0tIHpzS1ArSVFvSXRmRmx6ZDhwMUtP
            RmVnVjJtZWp2M3hwTjRsNXIvNGNYVk0K7k4tbRw3EI27qooSDg8UnzAJaObKHyA4
            1EjbBp4KMFJueHcVwJqL7wTEBvUguYD2eNwBdJS/xRwADt1rDGconQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age15pca2knfgtvh7erg7meupltmpl8hr42skwzfythd5qesdlz075msv92e6e
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3N29sMjg5OGQ0RWVhM25C
            MFFvZWpxSEpQdE10MkE1ekpEY2JxTVlUUGtFCjIyYWhWUUdjWGk2M0hMb3JFMDQ1
            aFY4R0hRYUVBZ3VNNlFWK3FMZ2RTYU0KLS0tIHdPdEpQWklrR3JsMUo1VU5GRHNh
            bzV6ZHVxUGNPRHNlaWRzd3prR2x4M28KvhNMPJDqC0EorZ+hgpMI+v7tBcBPiA3V
            RLaoCimI6BV7IUmnU/J2iyzjmG8AMaNaSfItgeJ13TWrUagtFPyvdA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1pcp35euleycnthrl7dr29x0awyhklr6aaucrkehzgytrg224dvlsnlhsej
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0Z0FXN1JEb3YvWnBKcWs0
            bkgwMFI0QzIraXJnRjNnbDgvUjVRNWViTFRVCmovUTV6YnhOMkVuQlBjUU1zdVc4
            c0lEWmF1SXhGVk9Cd1ZRSG1nZ0RkajgKLS0tIGNBTTZxaVpjQVR1Q0ZNd3VyQU5m
            UU1JcUkwRmx4bi9kQkN3NEpIY292U28Kwbl/3i24VSyLlbS43te1CKFaQ0+X7EEY
            YgewTvQu10iGaViOaoUy2Au6dK+rlmArf4cRUkWRDOnXgsgCpxLDtQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-10-01T05:12:02Z"
    mac: ENC[AES256_GCM,data:uStSEj6LmxN5ZIVQ1LZLeddC8SkGGqSDPb2pD4byTbEEb4b4WSQcwGrgiUqejDPrSQTTSJihqdfckhIGGn4juWYNYL8mq16kDnzdTqgKXltYMUUp302CKlcVhy0Wmkr4TepGxp5Xx3O7NT4NixBVxj8hYXydDTsYDvYU5JTWmQA=,iv:Dy62E+5lOiX78t40W5XF8Sz4/y7V9nfwNNdh7It7A6o=,tag:BJo9WanHt1TuMCePP3R45g==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.10.2
