passwd: ENC[AES256_GCM,data:tUc7gOk060O2vSAHaX64qwPE7NP9z6eDLsqrGT2HKDEUFbcssrFTnI2dHr92+vvcypjYnmEYfvv6R1Pkku1jtVqIpiVtwiGITQ==,iv:nJ8XyQrNauJ53eDG73ZB/QlEUQt/16HWmmQouBje31c=,tag:Z1HUHG/mXL548Oot5zAvoQ==,type:str]
age_key: ENC[AES256_GCM,data:eOR/w/Tt666zGsrXPedNm/ubYHnJdhI8wbiFWI3dCi3TitFhneITA3TPfvsVtwwAXeUHKB9MYD7YwABS9/liEHSw6o9zABbGAMg=,iv:4YBP0dy4va6Q24NF2g68KrAvWoWd1m9UgF7VN06sees=,tag:5nCepKcfzTtV44G66+9MOw==,type:str]
id_ed25519.pub: ENC[AES256_GCM,data:t8u4jSpuNnhTOloh0EaBLbRdtN8jS74fbMu1tXgxnAuO2oAgOCcyhIS1wC+OII3AscVV8mAq7hK6RoK5JuVM5/6v2zS0WTsCCEr2cbq/+1nzLBYE5x5IhQ==,iv:StwznPhRjKX4dGvEf8Sx7eDLLtV6gOSHjLN9lC1LDzs=,tag:pls1KIBv8iH+GTMwpC7ejQ==,type:str]
sops:
    shamir_threshold: 1
    age:
        - recipient: age1jtfn6xtwzg2n6jdjf3pkhzsw6ns5fqfexgyxk4k5cpxs79v3rv7qfhk05e
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3TGY0U1R6NDByMFVYSldu
            ZU1VREc0d0hjNUhZWVlucnl1REtzak01Y1M0CjJJR09RanFPcndzWFlRa3QxKzNn
            dEFHS0lOV0FTWEJKQjhZZW9KR1JSVEUKLS0tIFp4NzZNQ2F2RnlDWENwTE9LdXVw
            OUw5RnNSblpTS1MyZzUyLy9SbXNmYTQKqFpHVDQESy2ePVJjfFr3sZwVljLZmSu2
            JN+AYjkW+yDVySfSP0W1vY7W7PJT+VhkdLbUqOo9SIZU1nKmwYnjvw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age15el767ldhcl7exa0z7v78chzmjthsadavlcnnzhpfqp4sj6fcvtq0f95tk
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBESWg5SEJFdXpkWkJORWlz
            YzcrTVBIeHZIZVZrQ25vcDE3ZUpvSzJMUWdnCld0TnNXS1hwK3E5a3l0eHNuWm5K
            WlU1cGZXM1BKSXlXbmJ5eWxhbm9ONTgKLS0tIEowZmFWVlVBdXNVYWJQcWgyQVZo
            ZE9KZ0xXeUx6WFpwckZLWUJCcGM0cncKX7NtABQYv2Tc2neF2YjWvioW7Ep30la3
            DsG9dNrlTBiB1qo8nXQ4wlNfjvikxiSya7viH5j0xBxEsKGmzKtJ+A==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1sgvfec08pw9unyhf0q6mcm4p8t9qnq47mkx8q76ptf0y4v2lncnqwhlwcm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5NDVxTkpxT0JxV2hHZjVp
            ZzErOExsd3Y5TGJPVWQxdit3aTFia0h0Nm5RCkdEbDBWdzZUUDlqVnZQV2dXMGFV
            L3FSOFM3ZU1lcjZFYkN0YW5VVmVNYkkKLS0tIG9uL1pmV1BxVWQ1ZVhVcjFDRzJi
            WGJFaXFXbEFxTXhlcDJES2FYdWt5TlEK8fzcNorHi1+pAQ3svAncQh4Cap3uNzle
            SLeU7EoB1eabFuiy6LxPNgqQ9psbTyRJVm/irBXT8pv2im8Qzy8tmQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1lt0k6wfwl4drhg2wpkw4sazg5peymj5nrgn43mvsvkj0ua5ef4asdg2264
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0MTR5Uy9DWUVsOHdGUERv
            TUhrb1VqTWdjYjQ4SlllN1BkTXpHYVd6MVFFCmcrQnZ0WnZ6MHFCQS9nblg3V1h2
            YUNySlpEVUw3aEZGYWp4VkhlMDVadXcKLS0tIDFBUTU4eFBkSk5hb21iN3dxVDJ4
            aGhIM20yRk94M25XU08rb3I1VFlBRU0K5gEpa/QG418YvRnws8f0NAw9gzwVrQ5a
            qLJIYLMoXjj+q/aPmTy/taZdFJ1OVuP8FkU25zwYb+dNW6/FFk8JAw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1y5lqn9ayly64d55myxtxn70q5cn7e9wnqw9eeeddz04a0l6dp36sy3mgsx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxZE5uS0JSSGlGUzEvQldQ
            Qko2OWZpZzRVUFIycVVDYlpJUDU4SlAySWxNCk5ieWdNWGpXUnEyK2ZGQ1RZSDN0
            V3dqMnVOTEZJbk5TUkdyaGsrVE8xeWMKLS0tIGh0Z2JkNzVtRmdZZndZOThydURz
            cXkxQmlScEhmVklzVjRSUkZXUzM3ek0KTr07IgRKIQbr8sZZGC64Adbe9GSBLY7Y
            nUw/kpwOFaXK5CMcrov0Rq8KSbYPbL1euW3w/H6AIViqErb381OaAQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-09-16T21:05:00Z"
    mac: ENC[AES256_GCM,data:+lHCENvf0xdf/GzyDIDD1uX8epeGnhLTlSVrSZX19MMDAsvfNSWlHeNEyND6By+owFolM48j7I2RDNqCMegFc79vDleHZlYmDQ4PX/jye60Uo1VGtR8mqJ8Ilg4lW2KnxsJnR7nrzJsdS2cdazqYFA7WTJxuG7d6dphuMlw2syw=,iv:lWEretecYab4SG4muweMI4UjRpe7cVtNWOEw8Y/we50=,tag:8BNj7S+x26GJn9K4lAolLQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.10.2
