passwd: ENC[AES256_GCM,data:tUc7gOk060O2vSAHaX64qwPE7NP9z6eDLsqrGT2HKDEUFbcssrFTnI2dHr92+vvcypjYnmEYfvv6R1Pkku1jtVqIpiVtwiGITQ==,iv:nJ8XyQrNauJ53eDG73ZB/QlEUQt/16HWmmQouBje31c=,tag:Z1HUHG/mXL548Oot5zAvoQ==,type:str]
age_key: ENC[AES256_GCM,data:eOR/w/Tt666zGsrXPedNm/ubYHnJdhI8wbiFWI3dCi3TitFhneITA3TPfvsVtwwAXeUHKB9MYD7YwABS9/liEHSw6o9zABbGAMg=,iv:4YBP0dy4va6Q24NF2g68KrAvWoWd1m9UgF7VN06sees=,tag:5nCepKcfzTtV44G66+9MOw==,type:str]
id_ed25519.pub: ENC[AES256_GCM,data:t8u4jSpuNnhTOloh0EaBLbRdtN8jS74fbMu1tXgxnAuO2oAgOCcyhIS1wC+OII3AscVV8mAq7hK6RoK5JuVM5/6v2zS0WTsCCEr2cbq/+1nzLBYE5x5IhQ==,iv:StwznPhRjKX4dGvEf8Sx7eDLLtV6gOSHjLN9lC1LDzs=,tag:pls1KIBv8iH+GTMwpC7ejQ==,type:str]
wg_proton: ENC[AES256_GCM,data:Cu4Wz74IBCV3vpjuwuJAX7LjRuqBW+QW3ovY6V4h4WI22/fI6I8C1wMyGww=,iv:BXuW0Zf2pouR69XPkb0oSBlR3WpaWhIE04NzV4l8a3A=,tag:VvgELXlu+VrcwbIjnrsTlw==,type:str]
nebula_ca:
    cert: ENC[AES256_GCM,data:Xa3FSmNIS3275xkH9BwlbVInsaLEeHGAMFAdgCBgfW8DcP40iw8rggsPQSx5flZW2OJ98RFI9rbv3qRx8+8b0p+pbDaPH+EIl7xfrYrmcx+HGumWpEEm97rQXwJDgG2oy4sFh0Wt3EI/5UwyClP5f91ufEXjpEsyZDMARBmSI06AkNcWjmFKORxkWnox3sij3oo+0YsxB7kfTbnYSJ/m4epOV3NgjgL50tdKLlR2pcUfTTmxMDCm/uGFFeWcPbftSKZb00dZMuwo4hGY0QVa+U7xzMfQOedvcD9sq+2mCluHW+7Ecdqm1JNulEkV2lqNCIg3SlXpDCVNuhU=,iv:91lXQwrQkarg0iimCuqlb+qZ5zWBbObgfBg85pb8Ypw=,tag:F50hBrOKwpKB7oRynfhpkA==,type:str]
    key: ENC[AES256_GCM,data:5fI64KHjOIjHQG1CXZAaJNttnuFhxz1Ktupjm62t4TtfwQxR+3UMPatuwe0c5sFmIbw71+WM23tkssSmtiun0X3Pz0XePFyWahzsgzMXZwDnG/HVkbvTridkwmr8ex6K83tu1W+JGEGVM2w5mPP6HDd3kkWzOuGJBZQ8QPlhQL6Aey3Z2+zCFeXixUcm/qJDddGdxG/DioplNEP7yofMiO/8O+EdqQpF/GSt3Gm5,iv:OZh7yOYdY2dIMAjrncX5MOGkynq8L+tEbkZcbTX4taI=,tag:TjgjWkU6qON3K5vzlPQZLg==,type:str]
sops:
    shamir_threshold: 1
    age:
        - recipient: age1jtfn6xtwzg2n6jdjf3pkhzsw6ns5fqfexgyxk4k5cpxs79v3rv7qfhk05e
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUUWNqekhvakRsTjBPeUEy
            cmxCbFZ1ZGg3cWFQcjBKSVdZVzBPQ1NtVVZZCk1tOFhvbXB6RmZPY2NBcHRoNlhz
            Q1IzVWtLeExBQVZBdytJMW02amdkbGsKLS0tICthZlVkUU5XbWJxcUxzaG52THpS
            aS9oWHVsVjU0VnIyZkJQOEI5SkIySXMKSLxZXhk6UuiPhXNC1ViuQk1tvCC0NrsK
            kKX4ulKcV1T5OXCnprQQfrrh5MAEVBGeBd8emz9rtcn/8ZoQXyh8Rg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age15el767ldhcl7exa0z7v78chzmjthsadavlcnnzhpfqp4sj6fcvtq0f95tk
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHV1hBSTZWK3doSEJvclI1
            aCtCVFJOSmsyTHBheFZUSXZDQjZJVVE0OEY0CmlLaC9tdkRsRnprb1k1VkNub3VU
            TW0zaVZKYlNWREpLcWNPYUw0WDluVEEKLS0tIHQ1eGxQUEpORHFKZEhXc0Z2SDQ2
            KzBUMmM0SEdSbFptamdMTFE1MkVJOFUK4AAZAq1OS9QYVMeOEAONUZvRJ2GCDHj1
            CovLOmgdXvJmF1fkaoC8BWashWgD28pLmjmU7XoPKs0WsQKpI0eEJQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1zcfj8lpt8sry4sq9khrsyur2f9j8pezppz3asxjcu55mr23d4ats8dzrdc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNc1ozVlNnaDlFbks2M2dX
            N0hpcjJzTmJtS01iRHpCNGk3QjE3TSt0bUZRCjRYZWxPaDlFdDJFaXVzSVJuQ3Jl
            VEVUQVEyUnB3QTQ4K25lTTNKbnB0ZFEKLS0tIGFDSFIxOUgwMWo5UGNzU3J4aDJj
            UTI3TmpkZ29rWllSaXZ6eWZuT3g5RWcKP3+hbouzr/cl9/QUWO9KpGGBhbiNh9k4
            YS6P42SKme7zP859OD2vCbrd+r5lJjRUCtJa6Sa2A3ItZORK3ddkew==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1camvnsecm8hfnx66j7xg24lfgaeeamvtyr8kue0pdt5x92s5a9as9sew7r
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3L0lTWXd5WnJSRk9SbWpI
            d2M1YThoK3FsNHZ5RS9DeStCdytWQXFqRFdZCk4velJxb1pBYVcwNHUrVUQvWTVx
            elBLV2FMdnp3VzlqQUFSVE1VOVRvK0UKLS0tIEtqRGlYeDFHWkRtUGdmNjBoNm9U
            R2NJd2U4aEtPN2RpbHE4US9QdmQ4bjgKv8HqD2AEjlXBuolM/i/MG2si3oTYrQLO
            C23q3iBJdJ2mDWojdDfZfMzjRKei54o8QgNzgBdYYkejHfH6I3v5Dg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1lt0k6wfwl4drhg2wpkw4sazg5peymj5nrgn43mvsvkj0ua5ef4asdg2264
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrYVJPRjF4RGdpMlFIY0lL
            SEl6M0xXTUhsRVBUK20ra1JGVUo5V1p4bFRZCkZTeS9VK1FWTHBybzBlUFM1SnhH
            NlFyMGhab1h1ZndmZU1LSG5LMDRTNGMKLS0tIHNRMFpleVNyM0sxSXQ4czZFeGhN
            ejI0NWdlMXBiWkF5QjVvbWVPSURUdEUKmPzYkKQHQAV9vdu4rsY9VJonJJkd2dt2
            tG2Ho45caZOs9dMcb4eUNLcMGOLj0l0VTXlIfyMsvBxppOf62scZtw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1s0rkwq0c75z0zlue23evq77wq0qg4lfq4cwk4myunkrsz3k8xg8s2s0ymp
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRa1UvR3I1bEhsQVFkbDR0
            Y3NxWFdjQUorRUFYTFo3Y0d2QWYzYjZXMzJ3CjF3RkdBeU5hamc5bTdlbXlNSkhS
            dVpBY3BRK0xZMlZlY1RuSWZaRjNpR2MKLS0tIGRCYnNXcG5OU1NoYjY5KzFpNkFq
            WUdVVEp4RVloenkwcG45MmRCUGw3NWcKmoRcOwJHReuBAgRyegq1kww/8yRO7/4K
            ODnkNxodOd0w5dm/u6YIhkTPOyxb3Vx8ga+HxGCPbw8Gk2NdzEoL9A==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1rzwhhytjxxtz6jkz5xgzvvhvy883n92868h7ts0pv5dedglupa8qtgp4d5
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBicHJDa080d0FQcVo0UldZ
            dkdGak56NW56RFd1S05RR1hVK29PeGFwSXhFCjNhVlFZaEZ2eXdwZytLMHVmbERV
            NEdnbDQ0RDl4QVNUeGNTS3ZIQXpiV0UKLS0tIHRrbXJ1QzNGZkZmMFk2bjloODJH
            VHJGaXFqVVJ1RHh6YjdXOTdhVmduSzAKt67pGIHli53g5rO3tz24Tj7ckH7gvTFY
            SbWgBwrrJv4Jflwq548gNsgSua1met88Us6DuBl3aNwpfZYc+bqcfQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-10-01T05:12:02Z"
    mac: ENC[AES256_GCM,data:uStSEj6LmxN5ZIVQ1LZLeddC8SkGGqSDPb2pD4byTbEEb4b4WSQcwGrgiUqejDPrSQTTSJihqdfckhIGGn4juWYNYL8mq16kDnzdTqgKXltYMUUp302CKlcVhy0Wmkr4TepGxp5Xx3O7NT4NixBVxj8hYXydDTsYDvYU5JTWmQA=,iv:Dy62E+5lOiX78t40W5XF8Sz4/y7V9nfwNNdh7It7A6o=,tag:BJo9WanHt1TuMCePP3R45g==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.10.2
