passwd: ENC[AES256_GCM,data:tUc7gOk060O2vSAHaX64qwPE7NP9z6eDLsqrGT2HKDEUFbcssrFTnI2dHr92+vvcypjYnmEYfvv6R1Pkku1jtVqIpiVtwiGITQ==,iv:nJ8XyQrNauJ53eDG73ZB/QlEUQt/16HWmmQouBje31c=,tag:Z1HUHG/mXL548Oot5zAvoQ==,type:str]
age_key: ENC[AES256_GCM,data:eOR/w/Tt666zGsrXPedNm/ubYHnJdhI8wbiFWI3dCi3TitFhneITA3TPfvsVtwwAXeUHKB9MYD7YwABS9/liEHSw6o9zABbGAMg=,iv:4YBP0dy4va6Q24NF2g68KrAvWoWd1m9UgF7VN06sees=,tag:5nCepKcfzTtV44G66+9MOw==,type:str]
id_ed25519.pub: ENC[AES256_GCM,data:t8u4jSpuNnhTOloh0EaBLbRdtN8jS74fbMu1tXgxnAuO2oAgOCcyhIS1wC+OII3AscVV8mAq7hK6RoK5JuVM5/6v2zS0WTsCCEr2cbq/+1nzLBYE5x5IhQ==,iv:StwznPhRjKX4dGvEf8Sx7eDLLtV6gOSHjLN9lC1LDzs=,tag:pls1KIBv8iH+GTMwpC7ejQ==,type:str]
wg_proton: ENC[AES256_GCM,data:Cu4Wz74IBCV3vpjuwuJAX7LjRuqBW+QW3ovY6V4h4WI22/fI6I8C1wMyGww=,iv:BXuW0Zf2pouR69XPkb0oSBlR3WpaWhIE04NzV4l8a3A=,tag:VvgELXlu+VrcwbIjnrsTlw==,type:str]
sops:
    shamir_threshold: 1
    age:
        - recipient: age1jtfn6xtwzg2n6jdjf3pkhzsw6ns5fqfexgyxk4k5cpxs79v3rv7qfhk05e
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4M1dGR01jemlzK3pkL2xm
            cUNiNXBXdFRUMnF2aElpMGYyWkJwQlloWmlNClk3L21ycC8zM0U4aCtxWnNBUXlH
            eHh5d2JKaXVGTzZFcEZMZXFpejJxQjQKLS0tIDg2ZmRCNHFmS2RuOW1TTWpiNExI
            ZlYzbngrdXZzb2xGMElIMFlDcDMxREEKQF53d6FN8MSCYA6nyT1PkIHtj0osBgfE
            rUC60kQFU8emgYkpWrzEtprPpZ4T3mKtAbcSzKA9qM1YKKmW1hC5UQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age15el767ldhcl7exa0z7v78chzmjthsadavlcnnzhpfqp4sj6fcvtq0f95tk
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSVytnYUFVWHRhcUdXbnFi
            UGg5OSthaFo3UitZNjVOQzhROEQ5eUZUdXlZCm52UU1jUDEya2p5dWdQOEhVR3BB
            emxIdzhLVWNCTW1zNkNieDdCdkdNU3cKLS0tIGdoeXV5MFczeW54SE1oN1N1RG9B
            Qm5nVUlJVGJxN1EyOFhMWXNtMEkzRncKHwpafuGKDC6dJraObNQ3QIo6mWoBESZU
            QtTzjYWfg1vn9CPNSByxSW1dtMoCveWXMAkytRk8kZiRHY6+TrGTfw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1zcfj8lpt8sry4sq9khrsyur2f9j8pezppz3asxjcu55mr23d4ats8dzrdc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3cXp3RWtJRlMxZUg1eUZq
            UitLY053cVB3TVRya1RkQWpINVEydExpWFVRCnM4SlFKdm9Hc1p3MVFMUEwwM3ZW
            Qnl1Vk9MRzBxZ2FBOHd2dUdtOUtsa2sKLS0tIDNFM1VkV2VzQmoxa2IwYzFhQTR6
            d3hwNU1uMTNua1h1OTBWQXQ0YzZndmsKfjd28cPcrs7r+AJ7JPxuSav/qBuF0Vxg
            FDt36UIcB40BE4lplAk4rlpPglw9/VFhnn03y5eBJ8aGQEpWkfYs/A==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1sgvfec08pw9unyhf0q6mcm4p8t9qnq47mkx8q76ptf0y4v2lncnqwhlwcm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZdTlRVTIxRjl0amRnS2RE
            OHgyUk5GeW85bmtBWGs2SE1QTzlIbU1vY3hrCmlwRkNubWlGOGpxVjdDWGFZTFAy
            eU1vNU1nMzArN1JNbFJLK0hGb3RaakUKLS0tIGgyQlM5QjVLdkc1ekxsT2JBTGcw
            ME5YRXFRM1JzVTI4Nlh4VjdTTktFWnMKZZIhh/Fwjn9XbHCMxPBwQIBD05yl1KH/
            2o+XFdi+41qZF/BO1aoDcNuPK146NfV7E2AoikPaBtqRbHxNfOB/YQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1lt0k6wfwl4drhg2wpkw4sazg5peymj5nrgn43mvsvkj0ua5ef4asdg2264
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSaVlOeFNwZXh1SVBzendE
            T3NVQlk5RnByMXB4TWdsSWhHK1grdmd4VGdRCk0zTjJSd0R1eHhXdmpzZmRLdEdL
            SmR6WU9hZHlHd0o4cmtJc2hteDY2S3MKLS0tIGNPRGduVGJVSk8yUGE5U1lEd3pL
            MEhxNXhTbG5ZQkhtVW05NmhpWDdFeW8KJ3Qd9w/93b3BOVz4JB/j8R3KTPthHw6r
            2poK58D0hGLPYPU2F9zhk11f0rtabfQG3Nl2lTqyNayobOUcE0y8yQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1s0rkwq0c75z0zlue23evq77wq0qg4lfq4cwk4myunkrsz3k8xg8s2s0ymp
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlM0ZwMHhKT1JtSmJiajRa
            TnhsSGJjSXJBdVpEdEkxaVFCd1JKb3oyRUN3CmY4OWRVV1dvSDQrSlhlWUJUZmM4
            N0hMcmpTWUVJM0ZzWktqcnAySHkzeGcKLS0tIHV1K21UZTRvbHF5Rzk1YUZjQmVX
            dFpIdU91TCsvbVFpVGVQQzhKTlB3ejgKiI1bD0panjt+U24GJHH9gvWOURwdQ3LL
            s11Zsx5o2Dgt/ZUQsAUCNhDES24KjoxFxbwE+si8OPI2FYOzos4kbQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-09-17T20:28:31Z"
    mac: ENC[AES256_GCM,data:PkJtzKwxCpS8GvfjxHHaOPgDp/B+OSA64GcyKdT1nOcjG4t7ZYZu8P2xbTtCXE2LLy5Y96XQ8xEzwiC/aoRSn0lCDi0gpplu4KT9IU3JXy7VEVpqlrwUp3bw9svanJqOoAEsiIHmdogX7PbQ9yd1qUPwhxI6V5oX4eppssftSv4=,iv:eeTkgjAtihOuUz9MsOuPHHSpfAl3Adu2PQZhdazcUTY=,tag:i/uMINBGPbx3bDEMk+1Tnw==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.10.2
