passwd: ENC[AES256_GCM,data:tUc7gOk060O2vSAHaX64qwPE7NP9z6eDLsqrGT2HKDEUFbcssrFTnI2dHr92+vvcypjYnmEYfvv6R1Pkku1jtVqIpiVtwiGITQ==,iv:nJ8XyQrNauJ53eDG73ZB/QlEUQt/16HWmmQouBje31c=,tag:Z1HUHG/mXL548Oot5zAvoQ==,type:str]
age_key: ENC[AES256_GCM,data:eOR/w/Tt666zGsrXPedNm/ubYHnJdhI8wbiFWI3dCi3TitFhneITA3TPfvsVtwwAXeUHKB9MYD7YwABS9/liEHSw6o9zABbGAMg=,iv:4YBP0dy4va6Q24NF2g68KrAvWoWd1m9UgF7VN06sees=,tag:5nCepKcfzTtV44G66+9MOw==,type:str]
id_ed25519.pub: ENC[AES256_GCM,data:t8u4jSpuNnhTOloh0EaBLbRdtN8jS74fbMu1tXgxnAuO2oAgOCcyhIS1wC+OII3AscVV8mAq7hK6RoK5JuVM5/6v2zS0WTsCCEr2cbq/+1nzLBYE5x5IhQ==,iv:StwznPhRjKX4dGvEf8Sx7eDLLtV6gOSHjLN9lC1LDzs=,tag:pls1KIBv8iH+GTMwpC7ejQ==,type:str]
sops:
    shamir_threshold: 1
    age:
        - recipient: age1jtfn6xtwzg2n6jdjf3pkhzsw6ns5fqfexgyxk4k5cpxs79v3rv7qfhk05e
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4blpzcnozL1puSStBSVhD
            NjdEQWFDTlE5OVhWQlVCWG11MEszaGpsQXpzCkJWcnJFRkJPVmpGaHRHclhUc1BH
            WkNtM1BaaUtTdFVYVmt4RFBpN3VwMkkKLS0tIE5WbzkyVWJCdUhHaDBWVmdyZUNo
            QnNRdEc5Z0pTNk16MTlhREJXcG9MbGcKRWkRRZzvH0mJSRH+pjdBC1J0uMsjMmXA
            WdXfWwbAojyIFv5a+N2QxPNMTxt5EZErOgnfYKFqOIyj+oc81Z5JIg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age15el767ldhcl7exa0z7v78chzmjthsadavlcnnzhpfqp4sj6fcvtq0f95tk
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSa3FsWDlDYXpSbGpNV2pj
            RzdvNE5Sd2phOWZXNlViY3BIQ3FoK1FDNmxzCk5Ec29ZY0YweFBXeUgvT0tvQWw3
            QXFtRUxXSWx4VmYvbG10UXVDNERWTVUKLS0tIC80T01VVjcwK3NXNFo1MFRPOTA2
            UFdSRTNLTWx5K0d6bURTcFFoaFJ2anMKkSCuvN9UVfQKw809vF7IQFUGqlBcHJXM
            TgFSOrfpAktx6pqB4PlK6STwBb64q/wPFJfJetYHlL3NPrItfM7I+w==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1sgvfec08pw9unyhf0q6mcm4p8t9qnq47mkx8q76ptf0y4v2lncnqwhlwcm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPT2dCZ0cwblE4ejNSSnN4
            Ui80emV5WWlUeVVqTGxTY29sSitaZFhZSUJVCkZUYUlnQmkyWlV0Wlh4VzgxcUtI
            dHhUaEJCUjRUYTBqQWlwVUhxM2h3UTgKLS0tIDlOV01xYVdqVElkbERIYWxySkgx
            Z3BReXJuZHprSkY2WXprVGxlNzhWVlEKW00bsGttz2wz04HEubZmpLoHtWPW6Mzh
            eOLCI1kqLubwNnncyqPFlaVrmOLIdSVvr09xs8AsF3MhQBTlbzlEvw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1lt0k6wfwl4drhg2wpkw4sazg5peymj5nrgn43mvsvkj0ua5ef4asdg2264
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArNkRUNStXemh6a1piek9k
            ZkRsRFNKc2NLK3kyQVViYk1RSDA5eFhBSlJNCmV6SVBYYlhwN0d2YjkzVDJ1dDZS
            VGoyQlNUaUI4S0J6UExGVHBVMGkxeE0KLS0tIG0zaytwUHB6Yk5IeVk5czN5MDVv
            ZndmMmRnaE8yTHVwWXo3emNWa01STUUKerhUS7JhDXARlZsAn4K896KhnT3jd6TU
            L3KgRDZhtUTnHygGfZqtYdiATl/Yf62YGkS6jp3pqcoCVVlb1OZP6A==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1yptam40dlt97dmv6d0n9ytrwtxq9f2mqht8s7kdqjkmwax8nn4uq8hd9uh
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwVmMxT3k5encrSDFhaldM
            QmhNbG1MSnQyZ0M1c280WVFVWnRZMnhxR3gwCjVYczlzTlM5dmxhZGpwclhGOW1J
            QjZyaUdxYmYvbVd0SmxPZStaWUZwd0UKLS0tIERQN0I4ZGFIUGZPZURRMDRobW1l
            enphNFlOY2FnVVF6NWM2RFVobmVac2sKeikV+YhnX3JSyoBWOHQne4nWZ/TfjumD
            5iT/984NNsilYJoNRtqrpXE3Q7cAT2jIk26D/Dh8L9Iel5np3GcBcQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-09-16T21:05:00Z"
    mac: ENC[AES256_GCM,data:+lHCENvf0xdf/GzyDIDD1uX8epeGnhLTlSVrSZX19MMDAsvfNSWlHeNEyND6By+owFolM48j7I2RDNqCMegFc79vDleHZlYmDQ4PX/jye60Uo1VGtR8mqJ8Ilg4lW2KnxsJnR7nrzJsdS2cdazqYFA7WTJxuG7d6dphuMlw2syw=,iv:lWEretecYab4SG4muweMI4UjRpe7cVtNWOEw8Y/we50=,tag:8BNj7S+x26GJn9K4lAolLQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.10.2
